#!/bin/bash
# Exercises for Lesson 02: Filesystem Navigation
# Topic: Linux
# Solutions to practice problems from the lesson.

# === Exercise 1: Absolute vs Relative Paths ===
# Problem: Navigate the filesystem using absolute and relative paths with pwd/cd.
exercise_1() {
    echo "=== Exercise 1: Absolute vs Relative Paths and pwd/cd Patterns ==="
    echo ""
    echo "Scenario: You are managing a multi-project server and need to navigate"
    echo "efficiently between deeply nested directories."
    echo ""

    echo "--- Part A: Understand absolute vs relative paths ---"
    echo "Solution:"
    echo "  pwd                          # Print current working directory (absolute)"
    echo "  cd /var/log/nginx            # Absolute path — works from anywhere"
    echo "  cd ../apache2                # Relative path — go up one, then into apache2"
    echo "  cd ../../tmp                 # Go up two levels, then into /var/tmp"
    echo ""
    echo "  Explanation:"
    echo "    Absolute paths start with / and specify the full location."
    echo "    Relative paths are resolved from the current directory."
    echo "    '..' means parent directory, '.' means current directory."
    echo ""

    echo "--- Part B: Quick navigation shortcuts ---"
    echo "Solution:"
    echo "  cd ~               # Go to home directory (/home/username)"
    echo "  cd                 # Same as cd ~ (shortcut)"
    echo "  cd -               # Toggle back to previous directory"
    echo "  cd ~otheruser      # Go to another user's home directory"
    echo ""
    echo "  Explanation:"
    echo "    'cd -' is invaluable when switching between two directories."
    echo "    It prints the target path and changes to it. Equivalent to"
    echo "    'cd \$OLDPWD'. The shell tracks OLDPWD automatically."
    echo ""

    echo "--- Part C: Use CDPATH for frequently visited directories ---"
    echo "Solution (add to ~/.bashrc):"
    echo "  export CDPATH=.:/var/log:/etc:/opt/projects"
    echo ""
    echo "  Then simply type:"
    echo "  cd nginx           # Finds /var/log/nginx automatically"
    echo "  cd apache2         # Finds /etc/apache2 automatically"
    echo ""
    echo "  Explanation:"
    echo "    CDPATH works like PATH but for the cd command. The shell searches"
    echo "    each directory in CDPATH for the target. The leading '.' ensures"
    echo "    subdirectories of the current directory are checked first."
    echo ""

    echo "Verification:"
    echo "  pwd                # Confirm current location after navigation"
    echo "  echo \$OLDPWD      # Check previous directory"
}

# === Exercise 2: Finding Files with find/locate ===
# Problem: Search for files using find, locate, and glob patterns.
exercise_2() {
    echo "=== Exercise 2: Find Files with find/locate and Wildcards ==="
    echo ""
    echo "Scenario: A developer reports that log files are consuming too much disk."
    echo "You need to locate all large log files across the system."
    echo ""

    echo "--- Part A: Find files by name and type ---"
    echo "Solution:"
    echo "  find /var/log -name '*.log'                    # All .log files under /var/log"
    echo "  find /var/log -name '*.log' -type f            # Files only (not directories)"
    echo "  find /etc -iname '*.conf' -type f              # Case-insensitive match"
    echo "  find / -name 'nginx.conf' -type f 2>/dev/null  # Search entire filesystem"
    echo ""
    echo "  Explanation:"
    echo "    -name uses glob patterns (quote them to prevent shell expansion)."
    echo "    -iname is the case-insensitive variant."
    echo "    -type f = files, d = directories, l = symlinks."
    echo "    2>/dev/null suppresses 'Permission denied' errors."
    echo ""

    echo "--- Part B: Find files by size and modification time ---"
    echo "Solution:"
    echo "  find /var/log -size +100M -type f              # Files larger than 100MB"
    echo "  find /var/log -size +100M -exec ls -lh {} \\;   # Show details for each"
    echo "  find /home -mtime -7 -type f                   # Modified in last 7 days"
    echo "  find /tmp -atime +30 -type f                   # Accessed over 30 days ago"
    echo ""
    echo "  Explanation:"
    echo "    -size: +100M (greater than), -100M (less than), 100M (exactly)."
    echo "    -mtime -7 means modified within 7 days. +7 means older than 7 days."
    echo "    -exec runs a command on each result; {} is replaced by the filename."
    echo "    The \\; terminates -exec (escaped semicolon)."
    echo ""

    echo "--- Part C: Use locate for instant lookups ---"
    echo "Solution:"
    echo "  sudo updatedb                 # Rebuild the locate database"
    echo "  locate nginx.conf             # Instant lookup from database"
    echo "  locate -i readme              # Case-insensitive search"
    echo "  locate -c '*.py'              # Count matching files"
    echo ""
    echo "  Explanation:"
    echo "    locate searches a pre-built database (mlocate.db), making it"
    echo "    orders of magnitude faster than find for name-based searches."
    echo "    Downside: the database may be stale. Run updatedb to refresh."
    echo "    locate cannot filter by size, permissions, or modification time."
    echo ""

    echo "--- Part D: Combine find with actions ---"
    echo "Solution:"
    echo "  find /var/log -name '*.log' -size +50M -mtime +30 -exec ls -lh {} \\;"
    echo ""
    echo "  Explanation:"
    echo "    Combines multiple predicates: name pattern AND size AND age."
    echo "    All conditions must match (implicit AND). Use -o for OR logic."
    echo "    For bulk operations, use -exec ... {} + (plus) instead of \\; for"
    echo "    better performance — it batches arguments like xargs."
}

# === Exercise 3: Inodes, Hard Links, and Symlinks ===
# Problem: Understand and create hard links and symbolic links.
exercise_3() {
    echo "=== Exercise 3: Understanding Inodes, Hard Links, and Symlinks ==="
    echo ""
    echo "Scenario: You need to create links for a shared configuration file so"
    echo "multiple services can reference the same file without duplication."
    echo ""

    echo "--- Part A: Inspect inodes ---"
    echo "Solution:"
    echo "  ls -i /etc/hostname           # Show inode number of a file"
    echo "  stat /etc/hostname            # Full inode metadata (size, blocks, times)"
    echo "  df -i /                       # Show inode usage for filesystem"
    echo ""
    echo "  Explanation:"
    echo "    Every file has an inode — a data structure storing metadata (owner,"
    echo "    permissions, timestamps, block pointers). The filename is just a"
    echo "    directory entry pointing to an inode number. One inode can have"
    echo "    multiple directory entries (hard links)."
    echo ""

    echo "--- Part B: Create and verify hard links ---"
    echo "Solution:"
    echo "  ln /etc/shared/app.conf /opt/service-a/app.conf    # Create hard link"
    echo "  ls -li /etc/shared/app.conf /opt/service-a/app.conf  # Same inode number"
    echo "  stat /etc/shared/app.conf     # Link count shows 2"
    echo ""
    echo "  Explanation:"
    echo "    Hard links point to the same inode. Both names are equally 'real'."
    echo "    Deleting one name does not affect the other — data persists until"
    echo "    the link count reaches 0. Hard links cannot cross filesystem"
    echo "    boundaries and cannot link to directories."
    echo ""

    echo "--- Part C: Create and verify symbolic (soft) links ---"
    echo "Solution:"
    echo "  ln -s /etc/shared/app.conf /opt/service-b/app.conf   # Create symlink"
    echo "  ls -l /opt/service-b/app.conf   # Shows -> pointing to target"
    echo "  readlink /opt/service-b/app.conf # Print symlink target"
    echo "  readlink -f /opt/service-b/app.conf  # Resolve to absolute path"
    echo ""
    echo "  Explanation:"
    echo "    Symlinks are separate files containing a path to the target."
    echo "    They have their own inode (different from the target)."
    echo "    Symlinks CAN cross filesystems and CAN link to directories."
    echo "    If the target is deleted, the symlink becomes a 'dangling' link."
    echo ""

    echo "--- Part D: Find and clean up broken symlinks ---"
    echo "Solution:"
    echo "  find /opt -xtype l                  # Find broken (dangling) symlinks"
    echo "  find /opt -xtype l -exec rm {} \\;   # Remove broken symlinks"
    echo "  find /usr/local/bin -type l -ls      # List all symlinks with details"
    echo ""
    echo "  Explanation:"
    echo "    -xtype l matches symlinks whose target does not exist."
    echo "    Regular -type l matches all symlinks regardless of target."
    echo "    Broken symlinks accumulate over time when packages are removed"
    echo "    without cleaning up their links."
    echo ""

    echo "Key differences summary:"
    echo "  Hard link:  same inode, same filesystem, no directories, survives target deletion"
    echo "  Symlink:    own inode, cross-filesystem, links directories, breaks if target deleted"
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
echo "All exercises completed!"
