#!/bin/bash
# Exercises for Lesson 04: Text Processing
# Topic: Linux
# Solutions to practice problems from the lesson.

# === Exercise 1: grep with Regex Patterns ===
# Problem: Search files using grep with basic and extended regular expressions.
exercise_1() {
    echo "=== Exercise 1: grep with Regex Patterns (BRE, ERE) ==="
    echo ""
    echo "Scenario: You are analyzing web server access logs and application"
    echo "configuration files to find specific patterns."
    echo ""

    echo "--- Part A: Basic grep patterns ---"
    echo "Solution:"
    echo "  grep 'ERROR' /var/log/syslog                   # Literal string match"
    echo "  grep -i 'error' /var/log/syslog                # Case-insensitive"
    echo "  grep -n 'failed' /var/log/auth.log             # Show line numbers"
    echo "  grep -c 'GET' /var/log/nginx/access.log        # Count matching lines"
    echo "  grep -v '^#' /etc/nginx/nginx.conf             # Exclude comment lines"
    echo ""
    echo "  Explanation:"
    echo "    -i = ignore case. -n = line numbers. -c = count only."
    echo "    -v = invert match (show non-matching lines)."
    echo "    '^#' matches lines starting with '#' (BRE anchor)."
    echo ""

    echo "--- Part B: Extended regex (ERE) with grep -E ---"
    echo "Solution:"
    echo "  grep -E 'ERROR|WARN|CRIT' /var/log/syslog     # Match any of three words"
    echo "  grep -E '^[0-9]{1,3}\\.[0-9]{1,3}\\.' access.log  # Match IP-like patterns"
    echo "  grep -E '(GET|POST) /api/' access.log          # HTTP methods to /api/"
    echo "  grep -rE 'TODO|FIXME|HACK' /opt/project/src/   # Recursive search in code"
    echo ""
    echo "  Explanation:"
    echo "    -E enables ERE: | for alternation, + for one-or-more, ? for optional,"
    echo "    {} for quantifiers — without needing backslash escapes."
    echo "    -r = recursive (search all files in directory)."
    echo "    In BRE, you must write \\| and \\{n\\} (escaped). ERE is cleaner."
    echo ""

    echo "--- Part C: Context and output control ---"
    echo "Solution:"
    echo "  grep -A 3 'Exception' app.log         # Show 3 lines after each match"
    echo "  grep -B 2 'FATAL' app.log             # Show 2 lines before each match"
    echo "  grep -C 5 'segfault' /var/log/kern.log  # 5 lines before and after"
    echo "  grep -l 'password' /etc/*.conf         # List filenames only"
    echo "  grep -o '[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+' access.log  # Extract IPs only"
    echo ""
    echo "  Explanation:"
    echo "    -A (after), -B (before), -C (context) add surrounding lines."
    echo "    -l = list filenames with matches (not the lines themselves)."
    echo "    -o = output only the matched portion (not the full line)."
    echo "    These are essential for log analysis where context matters."
    echo ""

    echo "Verification:"
    echo "  grep --version   # Check if GNU grep (supports -P for PCRE)"
    echo "  grep -P '\\d{3}' means Perl-compatible regex (GNU grep only)"
}

# === Exercise 2: sed Stream Editing ===
# Problem: Use sed for text substitution, deletion, and in-place editing.
exercise_2() {
    echo "=== Exercise 2: sed Stream Editing (Substitution, Deletion, In-place) ==="
    echo ""
    echo "Scenario: You need to update configuration files across multiple servers,"
    echo "replacing old values and removing deprecated directives."
    echo ""

    echo "--- Part A: Basic substitution ---"
    echo "Solution:"
    echo "  sed 's/old/new/' file.txt              # Replace first occurrence per line"
    echo "  sed 's/old/new/g' file.txt             # Replace ALL occurrences per line"
    echo "  sed 's/old/new/gi' file.txt            # Case-insensitive global replace"
    echo "  sed 's|/usr/local|/opt|g' file.txt     # Use | as delimiter (for paths)"
    echo ""
    echo "  Explanation:"
    echo "    s/pattern/replacement/flags is the substitution command."
    echo "    g = global (all occurrences, not just the first)."
    echo "    i = case-insensitive (GNU sed extension)."
    echo "    Any character can be the delimiter — use | or # when patterns contain /."
    echo ""

    echo "--- Part B: In-place editing and backup ---"
    echo "Solution:"
    echo "  sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf    # In-place edit"
    echo "  sed -i.bak 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf  # With backup"
    echo ""
    echo "  Explanation:"
    echo "    -i modifies the file directly (no output to stdout)."
    echo "    -i.bak creates a backup file with .bak extension before modifying."
    echo "    ALWAYS use -i.bak in production — it is your safety net."
    echo "    On macOS, -i requires an argument: sed -i '' 's/.../' (empty string)."
    echo ""

    echo "--- Part C: Line deletion and selection ---"
    echo "Solution:"
    echo "  sed '/^#/d' config.conf               # Delete all comment lines"
    echo "  sed '/^$/d' config.conf               # Delete all blank lines"
    echo "  sed '/^#/d; /^$/d' config.conf        # Delete both comments and blanks"
    echo "  sed -n '10,20p' file.txt              # Print only lines 10-20"
    echo "  sed -n '/START/,/END/p' file.txt      # Print between two patterns"
    echo ""
    echo "  Explanation:"
    echo "    d = delete matched lines. p = print matched lines."
    echo "    -n suppresses default output (use with p to print only matches)."
    echo "    /pattern1/,/pattern2/ is a range address — matches lines between"
    echo "    the two patterns (inclusive)."
    echo ""

    echo "--- Part D: Multi-command sed and append/insert ---"
    echo "Solution:"
    echo "  sed -e 's/foo/bar/g' -e 's/baz/qux/g' file.txt  # Multiple substitutions"
    echo "  sed '/\\[server\\]/a\\    hostname = webserver01' config.ini  # Append after match"
    echo "  sed '/^server {/i\\# Added by automation' nginx.conf        # Insert before match"
    echo ""
    echo "  Explanation:"
    echo "    -e chains multiple editing commands in sequence."
    echo "    a\\ appends text after the matched line."
    echo "    i\\ inserts text before the matched line."
    echo "    These are essential for automated config management."
}

# === Exercise 3: awk Data Extraction ===
# Problem: Use awk to extract, transform, and report on structured text data.
exercise_3() {
    echo "=== Exercise 3: awk Data Extraction and Reporting ==="
    echo ""
    echo "Scenario: You have CSV-formatted application metrics and need to"
    echo "generate summary reports from the command line."
    echo ""

    echo "--- Part A: Column extraction and filtering ---"
    echo "Solution:"
    echo "  awk '{print \$1, \$4}' access.log       # Print columns 1 and 4"
    echo "  awk -F: '{print \$1, \$3}' /etc/passwd  # Use : as field separator"
    echo "  awk -F, '{print \$2}' data.csv          # Extract 2nd CSV column"
    echo "  awk '\$3 > 500 {print \$0}' access.log  # Filter: 3rd field > 500"
    echo ""
    echo "  Explanation:"
    echo "    \$1, \$2, etc. are field references. \$0 is the entire line."
    echo "    -F sets the field separator (default is whitespace)."
    echo "    Condition {action} — the action runs only when condition is true."
    echo "    awk automatically splits each line into fields."
    echo ""

    echo "--- Part B: Built-in variables and patterns ---"
    echo "Solution:"
    echo "  awk 'NR==1 {print}' file.txt                 # First line only (header)"
    echo "  awk 'NR>1 {print}' file.txt                  # Skip header"
    echo "  awk 'END {print NR}' file.txt                # Total line count"
    echo "  awk '/ERROR/ {count++} END {print count}' app.log  # Count ERROR lines"
    echo ""
    echo "  Explanation:"
    echo "    NR = current line Number (Record). NF = Number of Fields."
    echo "    BEGIN {...} runs before processing. END {...} runs after all input."
    echo "    /pattern/ matches lines containing the regex pattern."
    echo ""

    echo "--- Part C: Aggregation and reporting ---"
    echo "Solution:"
    echo "  # Sum values in column 5"
    echo "  awk '{sum += \$5} END {print \"Total:\", sum}' data.txt"
    echo ""
    echo "  # Average response time from access log"
    echo "  awk '{sum += \$NF; count++} END {print \"Avg:\", sum/count, \"ms\"}' access.log"
    echo ""
    echo "  # Count occurrences per unique value (like GROUP BY)"
    echo "  awk '{count[\$1]++} END {for (k in count) print k, count[k]}' access.log"
    echo ""
    echo "  Explanation:"
    echo "    \$NF is the last field (NF = number of fields, so \$NF = last one)."
    echo "    Associative arrays (count[key]) enable grouping and aggregation."
    echo "    This 'group by' pattern replaces: sort | uniq -c | sort -rn."
    echo ""

    echo "--- Part D: Formatted output ---"
    echo "Solution:"
    echo "  awk -F: '{printf \"%-20s UID=%-5s %s\\n\", \$1, \$3, \$7}' /etc/passwd"
    echo ""
    echo "  Explanation:"
    echo "    printf provides C-style formatting: %-20s = left-aligned 20-char string."
    echo "    Much more control than print for creating aligned tabular output."
    echo "    Combine with | sort or | head for top-N reports."
    echo ""

    echo "Verification:"
    echo "  awk --version   # Check if GNU awk (gawk) or mawk"
    echo "  gawk has more features (regex matching, getline, two-way pipes)"
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
echo "All exercises completed!"
