#!/bin/bash
# Exercises for Lesson 05: Permissions and Ownership
# Topic: Linux
# Solutions to practice problems from the lesson.

# === Exercise 1: chmod Numeric and Symbolic Modes ===
# Problem: Set file permissions using both numeric (octal) and symbolic notation.
exercise_1() {
    echo "=== Exercise 1: chmod Numeric and Symbolic Modes ==="
    echo ""
    echo "Scenario: You are deploying a web application and need to set correct"
    echo "permissions for scripts, config files, and data directories."
    echo ""

    echo "--- Part A: Numeric (octal) mode ---"
    echo "Solution:"
    echo "  chmod 755 deploy.sh          # rwxr-xr-x (owner: full, group/other: read+execute)"
    echo "  chmod 644 config.yaml        # rw-r--r-- (owner: read+write, group/other: read)"
    echo "  chmod 600 secrets.env        # rw------- (owner only, no group/other access)"
    echo "  chmod 750 /opt/app/          # rwxr-x--- (owner+group, no other)"
    echo ""
    echo "  Explanation:"
    echo "    Each digit represents: owner, group, other."
    echo "    Values: 4=read, 2=write, 1=execute. Add them together."
    echo "    7 = 4+2+1 = rwx, 6 = 4+2 = rw-, 5 = 4+1 = r-x, 4 = r--, 0 = ---"
    echo "    Common patterns: 755 (scripts), 644 (files), 600 (secrets), 750 (app dirs)."
    echo ""

    echo "--- Part B: Symbolic mode ---"
    echo "Solution:"
    echo "  chmod u+x script.sh          # Add execute for owner"
    echo "  chmod g+rw shared.txt        # Add read+write for group"
    echo "  chmod o-rwx private.key      # Remove all permissions for other"
    echo "  chmod a+r README.md          # Add read for all (a = all = u+g+o)"
    echo "  chmod u=rwx,g=rx,o= app/    # Set exact permissions (o= means none)"
    echo ""
    echo "  Explanation:"
    echo "    u=owner, g=group, o=other, a=all."
    echo "    + adds, - removes, = sets exactly."
    echo "    Symbolic mode is safer for targeted changes — it only modifies"
    echo "    what you specify, leaving other permissions untouched."
    echo ""

    echo "--- Part C: Recursive permissions with find ---"
    echo "Solution:"
    echo "  chmod -R 755 /opt/app/                     # Recursive (but see below)"
    echo "  find /opt/app -type d -exec chmod 755 {} \\;  # Directories: 755"
    echo "  find /opt/app -type f -exec chmod 644 {} \\;  # Files: 644"
    echo ""
    echo "  Explanation:"
    echo "    chmod -R applies the SAME mode to files and directories."
    echo "    This is usually wrong — files should not be executable (644),"
    echo "    but directories need execute to be traversable (755)."
    echo "    The find approach sets appropriate permissions for each type."
    echo ""

    echo "Verification:"
    echo "  ls -la file.txt       # Show permissions in long format"
    echo "  stat -c '%a %n' *     # Show octal permissions for all files"
}

# === Exercise 2: Special Permissions (SUID, SGID, Sticky Bit) ===
# Problem: Understand and configure SUID, SGID, and the sticky bit.
exercise_2() {
    echo "=== Exercise 2: Special Permissions (SUID, SGID, Sticky Bit) ==="
    echo ""
    echo "Scenario: Set up a shared project directory where team members can"
    echo "collaborate, and understand why certain system binaries need SUID."
    echo ""

    echo "--- Part A: SUID (Set User ID) ---"
    echo "Solution:"
    echo "  chmod u+s /usr/local/bin/custom-tool   # Set SUID"
    echo "  chmod 4755 /usr/local/bin/custom-tool  # Numeric: 4 prefix = SUID"
    echo "  ls -l /usr/bin/passwd                  # Example: -rwsr-xr-x (note the 's')"
    echo ""
    echo "  Explanation:"
    echo "    SUID makes a program run as the FILE OWNER, not the user who runs it."
    echo "    /usr/bin/passwd has SUID so regular users can modify /etc/shadow"
    echo "    (owned by root). The 's' replaces 'x' in the owner position."
    echo "    WARNING: SUID on scripts is ignored by most kernels for security."
    echo "    Only set SUID on trusted, audited binaries."
    echo ""

    echo "--- Part B: SGID (Set Group ID) ---"
    echo "Solution:"
    echo "  chmod g+s /opt/shared-project/         # Set SGID on directory"
    echo "  chmod 2775 /opt/shared-project/        # Numeric: 2 prefix = SGID"
    echo "  chown :developers /opt/shared-project/ # Set group ownership"
    echo ""
    echo "  Explanation:"
    echo "    SGID on a DIRECTORY: new files inherit the directory's group,"
    echo "    not the creating user's primary group. Essential for shared dirs."
    echo "    Without SGID, each user's files get their own primary group,"
    echo "    breaking group collaboration."
    echo "    SGID on a FILE: program runs with the file's group privileges."
    echo ""

    echo "--- Part C: Sticky bit ---"
    echo "Solution:"
    echo "  chmod +t /opt/shared-project/tmp/      # Set sticky bit"
    echo "  chmod 1777 /opt/shared-project/tmp/    # Numeric: 1 prefix = sticky"
    echo "  ls -ld /tmp                            # Shows 't' in the last position"
    echo ""
    echo "  Explanation:"
    echo "    Sticky bit on a directory: only the file OWNER (or root) can delete"
    echo "    or rename files, even if others have write permission to the directory."
    echo "    /tmp uses 1777: everyone can create files, but only owners can delete."
    echo "    Without sticky bit, any user with write access to the directory could"
    echo "    delete anyone's files."
    echo ""

    echo "--- Part D: Find files with special permissions (security audit) ---"
    echo "Solution:"
    echo "  find / -perm -4000 -type f 2>/dev/null   # Find all SUID files"
    echo "  find / -perm -2000 -type f 2>/dev/null   # Find all SGID files"
    echo "  find / -perm -1000 -type d 2>/dev/null   # Find all sticky-bit directories"
    echo ""
    echo "  Explanation:"
    echo "    -perm -4000 matches files where the SUID bit is set (among others)."
    echo "    Regular SUID audit is a security best practice — unexpected SUID"
    echo "    binaries may indicate compromise or misconfiguration."
    echo "    Compare results against a known-good baseline periodically."
}

# === Exercise 3: ACLs and umask Configuration ===
# Problem: Configure fine-grained access with ACLs and set default permissions with umask.
exercise_3() {
    echo "=== Exercise 3: ACLs and umask Configuration ==="
    echo ""
    echo "Scenario: A project needs specific users from different groups to have"
    echo "different access levels — something standard Unix permissions cannot do."
    echo ""

    echo "--- Part A: Set and view ACLs ---"
    echo "Solution:"
    echo "  setfacl -m u:alice:rw /opt/project/report.csv    # Give alice read+write"
    echo "  setfacl -m g:auditors:r /opt/project/report.csv  # Give auditors group read"
    echo "  setfacl -m u:bob:--- /opt/project/report.csv     # Deny bob all access"
    echo "  getfacl /opt/project/report.csv                   # View ACL entries"
    echo ""
    echo "  Explanation:"
    echo "    -m = modify ACL. u:user:perms or g:group:perms."
    echo "    ACLs extend standard owner/group/other with per-user and per-group rules."
    echo "    Files with ACLs show a '+' in ls -l output (e.g., -rw-r--r--+)."
    echo "    The filesystem must be mounted with ACL support (default on ext4, xfs)."
    echo ""

    echo "--- Part B: Default ACLs for directories ---"
    echo "Solution:"
    echo "  setfacl -d -m u:alice:rw /opt/project/            # Default ACL for new files"
    echo "  setfacl -d -m g:developers:rwx /opt/project/      # Default for developers group"
    echo "  getfacl /opt/project/                              # View including defaults"
    echo ""
    echo "  Explanation:"
    echo "    -d sets DEFAULT ACLs — applied automatically to new files and"
    echo "    subdirectories created within the directory."
    echo "    This solves the problem of every new file needing manual ACL setup."
    echo "    Default ACLs only apply to directories, not files."
    echo ""

    echo "--- Part C: Remove ACLs ---"
    echo "Solution:"
    echo "  setfacl -x u:alice /opt/project/report.csv        # Remove alice's ACL entry"
    echo "  setfacl -b /opt/project/report.csv                # Remove ALL ACL entries"
    echo "  setfacl -k /opt/project/                          # Remove default ACLs only"
    echo ""
    echo "  Explanation:"
    echo "    -x removes a specific entry. -b removes all ACLs (back to standard)."
    echo "    -k removes only default ACLs from a directory."
    echo ""

    echo "--- Part D: umask configuration ---"
    echo "Solution:"
    echo "  umask                  # Show current umask (e.g., 0022)"
    echo "  umask 027              # Set: files=640, directories=750"
    echo "  umask 077              # Restrictive: files=600, directories=700"
    echo ""
    echo "  Explanation:"
    echo "    umask is subtracted from default permissions (666 for files, 777 for dirs)."
    echo "    umask 022: files=644 (666-022), dirs=755 (777-022). Standard default."
    echo "    umask 027: files=640, dirs=750. Good for shared servers."
    echo "    umask 077: files=600, dirs=700. Most restrictive (owner-only access)."
    echo "    Set permanently in ~/.bashrc or /etc/profile for system-wide default."
    echo ""

    echo "Verification:"
    echo "  touch testfile && ls -l testfile   # Check default permissions with current umask"
    echo "  getfacl testfile                   # View ACL (should show standard entries only)"
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
echo "All exercises completed!"
