#!/bin/bash
# Exercises for Lesson 15: Container Internals
# Topic: Linux
# Solutions to practice problems from the lesson.

# === Exercise 1: Linux Namespaces ===
# Problem: Demonstrate how Linux namespaces provide process isolation,
#          using unshare to create isolated environments.
exercise_1() {
    echo "=== Exercise 1: Linux Namespaces ==="
    echo ""
    echo "Scenario: Understand the building blocks of containers by manually"
    echo "creating isolated namespaces using the unshare command."
    echo ""

    echo "--- Part A: Namespace Types Overview ---"
    echo "Solution:"
    echo "  # View namespaces of a process"
    echo "  ls -la /proc/self/ns/"
    echo ""
    echo "  Namespace types:"
    echo "    pid   - Process ID isolation (PID 1 inside container)"
    echo "    net   - Network stack isolation (own interfaces, routing, ports)"
    echo "    mnt   - Mount point isolation (own filesystem view)"
    echo "    uts   - Hostname/domain isolation (own hostname)"
    echo "    ipc   - Inter-process communication isolation (semaphores, shared memory)"
    echo "    user  - User/group ID mapping (root inside, unprivileged outside)"
    echo "    cgroup - Cgroup hierarchy isolation"
    echo ""
    echo "  # Compare namespaces between processes"
    echo "  readlink /proc/1/ns/pid         # Init's PID namespace"
    echo "  readlink /proc/self/ns/pid      # Current process's PID namespace"
    echo "  # Same inode number = same namespace"
    echo ""
    echo "  Explanation:"
    echo "    Each namespace type isolates a different kernel resource"
    echo "    Containers use ALL namespace types together for full isolation"
    echo "    Namespaces are files in /proc/PID/ns/ — same inode = same namespace"
    echo ""

    echo "--- Part B: PID and UTS Namespace Isolation ---"
    echo "Solution:"
    echo "  # Create a new PID + UTS namespace (requires root)"
    echo "  sudo unshare --pid --uts --fork --mount-proc bash"
    echo ""
    echo "  # Inside the new namespace:"
    echo "  hostname container-test          # Change hostname (isolated)"
    echo "  hostname                          # Shows 'container-test'"
    echo "  ps aux                            # Only shows processes in this namespace"
    echo "  echo \$\$                          # PID 1 inside the namespace"
    echo "  exit                              # Return to host"
    echo ""
    echo "  # On the host:"
    echo "  hostname                          # Still the original hostname"
    echo ""
    echo "  Flag explanation:"
    echo "    --pid        Create new PID namespace"
    echo "    --uts        Create new UTS (hostname) namespace"
    echo "    --fork       Fork before exec (required for PID namespace to work)"
    echo "    --mount-proc Mount a new /proc so ps/top work correctly inside"
    echo ""
    echo "  Explanation:"
    echo "    Without --fork, the calling process keeps its old PID namespace"
    echo "    Without --mount-proc, ps would show host processes via the old /proc"
    echo "    PID 1 inside the namespace is the init process (bash in this case)"
    echo "    Killing PID 1 inside terminates all processes in the namespace"
    echo ""

    echo "--- Part C: Network Namespace Isolation ---"
    echo "Solution:"
    echo "  # Create a named network namespace"
    echo "  sudo ip netns add testns"
    echo ""
    echo "  # Run a command inside the namespace"
    echo "  sudo ip netns exec testns ip addr show     # Only loopback, no eth0"
    echo "  sudo ip netns exec testns ip link set lo up # Bring up loopback"
    echo ""
    echo "  # Create a veth pair to connect host and namespace"
    echo "  sudo ip link add veth-host type veth peer name veth-ns"
    echo "  sudo ip link set veth-ns netns testns"
    echo ""
    echo "  # Configure IP addresses"
    echo "  sudo ip addr add 10.200.0.1/24 dev veth-host"
    echo "  sudo ip link set veth-host up"
    echo "  sudo ip netns exec testns ip addr add 10.200.0.2/24 dev veth-ns"
    echo "  sudo ip netns exec testns ip link set veth-ns up"
    echo ""
    echo "  # Test connectivity"
    echo "  ping -c 2 10.200.0.2                       # From host to namespace"
    echo "  sudo ip netns exec testns ping -c 2 10.200.0.1  # From namespace to host"
    echo ""
    echo "  # Cleanup"
    echo "  sudo ip netns del testns"
    echo ""
    echo "  Explanation:"
    echo "    veth pairs are virtual ethernet cables connecting two namespaces"
    echo "    Each end of the veth pair lives in a different network namespace"
    echo "    This is exactly how Docker connects containers to the host bridge"
    echo "    Named namespaces persist in /var/run/netns/ until deleted"
}

# === Exercise 2: cgroups v2 Resource Limiting ===
# Problem: Use cgroups v2 to limit CPU, memory, and I/O resources
#          for a process group.
exercise_2() {
    echo "=== Exercise 2: cgroups v2 Resource Limiting ==="
    echo ""
    echo "Scenario: Limit resources for a batch processing application to prevent"
    echo "it from consuming all system resources and impacting other services."
    echo ""

    echo "--- Part A: cgroups v2 Structure and Setup ---"
    echo "Solution:"
    echo "  # Verify cgroups v2 is active"
    echo "  mount | grep cgroup2"
    echo "  # Should show: cgroup2 on /sys/fs/cgroup type cgroup2"
    echo ""
    echo "  # View cgroup hierarchy"
    echo "  ls /sys/fs/cgroup/"
    echo "  cat /sys/fs/cgroup/cgroup.controllers    # Available controllers"
    echo "  # Output: cpu cpuset io memory pids"
    echo ""
    echo "  # Create a new cgroup"
    echo "  sudo mkdir /sys/fs/cgroup/batch-jobs"
    echo ""
    echo "  # Enable controllers for the new cgroup"
    echo "  echo '+cpu +memory +io +pids' | sudo tee /sys/fs/cgroup/cgroup.subtree_control"
    echo ""
    echo "  Explanation:"
    echo "    cgroups v2 uses a unified hierarchy (single mount point)"
    echo "    Controllers must be enabled at each level of the hierarchy"
    echo "    cgroup.subtree_control enables controllers for child cgroups"
    echo "    Each cgroup is a directory; settings are files within it"
    echo ""

    echo "--- Part B: Setting Resource Limits ---"
    echo "Solution:"
    echo "  # Memory limit: 512 MB hard limit, 384 MB high watermark"
    echo "  echo 536870912 | sudo tee /sys/fs/cgroup/batch-jobs/memory.max"
    echo "  echo 402653184 | sudo tee /sys/fs/cgroup/batch-jobs/memory.high"
    echo ""
    echo "  # CPU limit: 150% of one core (1.5 cores max)"
    echo "  echo '150000 100000' | sudo tee /sys/fs/cgroup/batch-jobs/cpu.max"
    echo "  # Format: QUOTA PERIOD (microseconds). 150000/100000 = 150% = 1.5 cores"
    echo ""
    echo "  # PID limit: max 100 processes"
    echo "  echo 100 | sudo tee /sys/fs/cgroup/batch-jobs/pids.max"
    echo ""
    echo "  # I/O limit: 50 MB/s read, 20 MB/s write on device 8:0 (sda)"
    echo "  echo '8:0 rbps=52428800 wbps=20971520' | sudo tee /sys/fs/cgroup/batch-jobs/io.max"
    echo ""
    echo "  Explanation:"
    echo "    memory.max = hard limit (OOM killed if exceeded)"
    echo "    memory.high = soft limit (throttled, not killed)"
    echo "    cpu.max = QUOTA/PERIOD. 150000/100000 means 150% of one CPU"
    echo "    pids.max prevents fork bombs from consuming all PIDs"
    echo "    io.max uses device major:minor numbers (find with lsblk -o NAME,MAJ:MIN)"
    echo ""

    echo "--- Part C: Assigning Processes and Monitoring ---"
    echo "Solution:"
    echo "  # Move a running process to the cgroup"
    echo "  echo \$(pgrep batch-worker) | sudo tee /sys/fs/cgroup/batch-jobs/cgroup.procs"
    echo ""
    echo "  # Run a new process directly in the cgroup"
    echo "  sudo systemd-run --scope --slice=batch-jobs.slice /opt/batch/worker.sh"
    echo ""
    echo "  # Monitor resource usage"
    echo "  cat /sys/fs/cgroup/batch-jobs/memory.current        # Current memory usage"
    echo "  cat /sys/fs/cgroup/batch-jobs/cpu.stat              # CPU usage statistics"
    echo "  cat /sys/fs/cgroup/batch-jobs/pids.current           # Current PID count"
    echo "  cat /sys/fs/cgroup/batch-jobs/memory.events          # OOM events count"
    echo ""
    echo "  # Using systemd (preferred method for production)"
    echo "  # In the service unit [Service] section:"
    echo "  echo \"  MemoryMax=512M\""
    echo "  echo \"  CPUQuota=150%\""
    echo "  echo \"  TasksMax=100\""
    echo "  echo \"  IOWriteBandwidthMax=/dev/sda 20M\""
    echo ""
    echo "  Explanation:"
    echo "    Write PID to cgroup.procs to move a running process"
    echo "    systemd-run is convenient for one-off cgroup-limited commands"
    echo "    systemd service directives are the cleanest way to set cgroup limits"
    echo "    memory.events tracks oom, oom_kill, high, max events"
    echo ""

    echo "--- Cleanup ---"
    echo "  # Remove a cgroup (must have no processes)"
    echo "  sudo rmdir /sys/fs/cgroup/batch-jobs"
}

# === Exercise 3: Building a Minimal Container from Scratch ===
# Problem: Combine namespaces, cgroups, and chroot to build a minimal
#          container without Docker or any container runtime.
exercise_3() {
    echo "=== Exercise 3: Building a Minimal Container from Scratch ==="
    echo ""
    echo "Scenario: Understand container internals by building one manually"
    echo "using chroot, namespaces, and cgroups — the primitives that Docker uses."
    echo ""

    echo "--- Part A: Create a Minimal Root Filesystem ---"
    echo "Solution:"
    echo "  # Create container rootfs directory"
    echo "  ROOTFS=/tmp/mycontainer"
    echo "  mkdir -p \$ROOTFS/{bin,lib,lib64,proc,sys,dev,etc,tmp}"
    echo ""
    echo "  # Copy a statically linked shell (busybox)"
    echo "  cp \$(which busybox) \$ROOTFS/bin/ 2>/dev/null || echo '(install busybox first)'"
    echo ""
    echo "  # Or use debootstrap for a full Debian rootfs"
    echo "  sudo debootstrap --variant=minbase bookworm \$ROOTFS http://deb.debian.org/debian/"
    echo ""
    echo "  # Create essential device nodes"
    echo "  sudo mknod -m 666 \$ROOTFS/dev/null c 1 3"
    echo "  sudo mknod -m 666 \$ROOTFS/dev/zero c 1 5"
    echo "  sudo mknod -m 666 \$ROOTFS/dev/random c 1 8"
    echo "  sudo mknod -m 666 \$ROOTFS/dev/urandom c 1 9"
    echo ""
    echo "  Explanation:"
    echo "    A container rootfs is just a directory tree that looks like / to the container"
    echo "    busybox provides sh, ls, ps, etc. in a single static binary"
    echo "    debootstrap creates a real Debian installation (heavier but full-featured)"
    echo "    Device nodes are needed for /dev/null, /dev/zero, etc."
    echo ""

    echo "--- Part B: Enter the Container with Namespaces ---"
    echo "Solution:"
    echo "  # Combine unshare + chroot for full isolation"
    echo "  sudo unshare --pid --uts --ipc --mount --net --fork \\"
    echo "      chroot \$ROOTFS /bin/sh -c '"
    echo "          mount -t proc proc /proc"
    echo "          mount -t sysfs sysfs /sys"
    echo "          hostname my-container"
    echo "          echo \"Inside container:\" && hostname"
    echo "          ps aux"
    echo "          echo \"PID: \$\$\""
    echo "      '"
    echo ""
    echo "  Flags explained:"
    echo "    --pid      Isolate process IDs (PID 1 inside)"
    echo "    --uts      Isolate hostname"
    echo "    --ipc      Isolate IPC (shared memory, semaphores)"
    echo "    --mount    Isolate mount points"
    echo "    --net      Isolate network (no network by default)"
    echo "    --fork     Fork so child gets PID 1 in new namespace"
    echo "    chroot     Change apparent root directory to \$ROOTFS"
    echo ""
    echo "  Explanation:"
    echo "    This is essentially what 'docker run' does under the hood"
    echo "    The process sees \$ROOTFS as / and only its own processes"
    echo "    No network access unless a veth pair is configured (like Exercise 1 Part C)"
    echo ""

    echo "--- Part C: Add Resource Limits (The Complete Picture) ---"
    echo "Solution:"
    cat << 'SCRIPT'
  #!/bin/bash
  # mini-container.sh — a container in ~20 lines

  ROOTFS="/tmp/mycontainer"
  CGROUP="/sys/fs/cgroup/mini-container"
  MEMORY_LIMIT=134217728    # 128 MB
  PID_LIMIT=50

  # 1. Create cgroup with limits
  sudo mkdir -p "$CGROUP"
  echo "$MEMORY_LIMIT" | sudo tee "$CGROUP/memory.max" > /dev/null
  echo "$PID_LIMIT" | sudo tee "$CGROUP/pids.max" > /dev/null

  # 2. Move current shell to the cgroup
  echo $$ | sudo tee "$CGROUP/cgroup.procs" > /dev/null

  # 3. Enter namespaces + chroot
  exec sudo unshare --pid --uts --ipc --mount --fork \
      chroot "$ROOTFS" /bin/sh -c '
          mount -t proc proc /proc
          hostname mini-container
          exec /bin/sh
      '
SCRIPT
    echo ""
    echo "  Explanation:"
    echo "    Step 1: Create a cgroup and set memory/PID limits"
    echo "    Step 2: Move the current process into the cgroup"
    echo "    Step 3: Enter all namespaces and chroot into the rootfs"
    echo "    This gives you: filesystem isolation + PID isolation + resource limits"
    echo "    What's missing vs Docker: image layers, union filesystem, container networking,"
    echo "    seccomp filters, capability dropping, storage drivers"
    echo ""

    echo "--- Docker Equivalents ---"
    echo "  Namespace       | Docker flag"
    echo "  ----------------+---------------------------"
    echo "  --pid           | (always enabled)"
    echo "  --net           | --network=none"
    echo "  --uts           | --hostname=myhost"
    echo "  --mount + chroot| -v /host:/container"
    echo "  cgroup limits   | --memory=128m --pids-limit=50"
    echo ""

    echo "--- Cleanup ---"
    echo "  sudo rmdir /sys/fs/cgroup/mini-container 2>/dev/null"
    echo "  sudo rm -rf /tmp/mycontainer"
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
echo "All exercises completed!"
