#!/bin/bash
# Exercises for Lesson 16: Storage Management
# Topic: Linux
# Solutions to practice problems from the lesson.

# === Exercise 1: LVM Setup and Management ===
# Problem: Set up and manage Logical Volume Manager (LVM) for flexible
#          disk management with snapshots and resizing.
exercise_1() {
    echo "=== Exercise 1: LVM Setup and Management ==="
    echo ""
    echo "Scenario: A database server needs flexible storage that can be resized"
    echo "without downtime and supports snapshots for backups."
    echo ""

    echo "--- Part A: Creating the LVM Stack (PV -> VG -> LV) ---"
    echo "Solution:"
    echo "  # Step 1: Create Physical Volumes (PV) from raw disks"
    echo "  sudo pvcreate /dev/sdb /dev/sdc"
    echo ""
    echo "  # Verify"
    echo "  sudo pvs             # Brief summary"
    echo "  sudo pvdisplay       # Detailed info"
    echo ""
    echo "  # Step 2: Create a Volume Group (VG) from physical volumes"
    echo "  sudo vgcreate data-vg /dev/sdb /dev/sdc"
    echo ""
    echo "  # Verify"
    echo "  sudo vgs             # Brief summary"
    echo "  sudo vgdisplay       # Detailed info (shows free extents)"
    echo ""
    echo "  # Step 3: Create Logical Volumes (LV)"
    echo "  sudo lvcreate -L 50G -n db-lv data-vg         # Fixed size: 50 GB"
    echo "  sudo lvcreate -l 80%FREE -n logs-lv data-vg   # 80% of remaining free space"
    echo ""
    echo "  # Verify"
    echo "  sudo lvs             # Brief summary"
    echo "  sudo lvdisplay       # Detailed info"
    echo ""
    echo "  # Step 4: Create filesystem and mount"
    echo "  sudo mkfs.ext4 /dev/data-vg/db-lv"
    echo "  sudo mkfs.xfs /dev/data-vg/logs-lv"
    echo "  sudo mkdir -p /data/db /data/logs"
    echo "  sudo mount /dev/data-vg/db-lv /data/db"
    echo "  sudo mount /dev/data-vg/logs-lv /data/logs"
    echo ""
    echo "  Explanation:"
    echo "    PV = Physical Volume (raw disk or partition)"
    echo "    VG = Volume Group (pool of storage from one or more PVs)"
    echo "    LV = Logical Volume (usable volume carved from a VG, like a partition)"
    echo "    -L specifies exact size; -l specifies in extents or percentage"
    echo "    LVM path: /dev/VG_NAME/LV_NAME"
    echo ""

    echo "--- Part B: Resizing Logical Volumes ---"
    echo "Solution:"
    echo "  # Extend a logical volume (online, no downtime)"
    echo "  sudo lvextend -L +20G /dev/data-vg/db-lv      # Add 20 GB"
    echo "  sudo resize2fs /dev/data-vg/db-lv              # Grow ext4 filesystem"
    echo "  # For XFS:"
    echo "  sudo xfs_growfs /data/logs                      # XFS uses mount point, not device"
    echo ""
    echo "  # Combined: extend LV and filesystem in one command"
    echo "  sudo lvextend -L +20G --resizefs /dev/data-vg/db-lv"
    echo ""
    echo "  # Shrink (ext4 only, NOT supported on XFS)"
    echo "  sudo umount /data/db                            # Must unmount first!"
    echo "  sudo e2fsck -f /dev/data-vg/db-lv               # fsck required before shrink"
    echo "  sudo resize2fs /dev/data-vg/db-lv 30G           # Shrink filesystem to 30 GB"
    echo "  sudo lvreduce -L 30G /dev/data-vg/db-lv         # Shrink LV to match"
    echo "  sudo mount /dev/data-vg/db-lv /data/db"
    echo ""
    echo "  # Add a new disk to expand the volume group"
    echo "  sudo pvcreate /dev/sdd"
    echo "  sudo vgextend data-vg /dev/sdd"
    echo "  # Now there's more free space in data-vg for extending LVs"
    echo ""
    echo "  Explanation:"
    echo "    Extending is safe and can be done online (no downtime)"
    echo "    Shrinking is risky — always backup first, and remember: XFS cannot shrink"
    echo "    --resizefs flag handles both LV and filesystem in one step"
    echo "    vgextend adds a new physical disk to the pool without disturbing existing data"
    echo ""

    echo "--- Part C: LVM Snapshots ---"
    echo "Solution:"
    echo "  # Create a snapshot (instant, copy-on-write)"
    echo "  sudo lvcreate -L 10G -s -n db-snapshot /dev/data-vg/db-lv"
    echo "  # -s = snapshot, -L = space reserved for changes"
    echo ""
    echo "  # Mount the snapshot (read-only for backup)"
    echo "  sudo mkdir -p /mnt/db-snapshot"
    echo "  sudo mount -o ro /dev/data-vg/db-snapshot /mnt/db-snapshot"
    echo ""
    echo "  # Backup from the snapshot (consistent point-in-time copy)"
    echo "  tar czf /backup/db-$(date +%Y%m%d).tar.gz -C /mnt/db-snapshot ."
    echo ""
    echo "  # Remove snapshot after backup"
    echo "  sudo umount /mnt/db-snapshot"
    echo "  sudo lvremove /dev/data-vg/db-snapshot"
    echo ""
    echo "  # Monitor snapshot usage (must not reach 100%!)"
    echo "  sudo lvs -o lv_name,lv_size,data_percent,snap_percent"
    echo ""
    echo "  Explanation:"
    echo "    Snapshots are instant regardless of volume size (copy-on-write)"
    echo "    The -L size is for storing changes to the original since snapshot creation"
    echo "    If snapshot fills to 100%, it becomes invalid and is auto-dropped"
    echo "    Always size snapshots generously and monitor with lvs"
    echo ""

    echo "--- Verification ---"
    echo "  sudo pvs && sudo vgs && sudo lvs   # Quick overview of entire LVM stack"
    echo "  df -h /data/db /data/logs            # Verify mounted sizes"
}

# === Exercise 2: RAID Configuration ===
# Problem: Configure software RAID using mdadm for redundancy and
#          performance on a Linux server.
exercise_2() {
    echo "=== Exercise 2: RAID Configuration with mdadm ==="
    echo ""
    echo "Scenario: Set up software RAID for a file server that requires"
    echo "data redundancy and acceptable read performance."
    echo ""

    echo "--- Part A: Creating RAID Arrays ---"
    echo "Solution:"
    echo "  # RAID 1 (Mirror): 2 disks, full redundancy"
    echo "  sudo mdadm --create /dev/md0 --level=1 --raid-devices=2 /dev/sdb /dev/sdc"
    echo ""
    echo "  # RAID 5 (Striping with parity): 3+ disks, one disk fault tolerance"
    echo "  sudo mdadm --create /dev/md1 --level=5 --raid-devices=3 /dev/sdd /dev/sde /dev/sdf"
    echo ""
    echo "  # RAID 10 (Mirror + Stripe): 4 disks, best performance + redundancy"
    echo "  sudo mdadm --create /dev/md2 --level=10 --raid-devices=4 /dev/sdg /dev/sdh /dev/sdi /dev/sdj"
    echo ""
    echo "  # With a spare disk (auto-rebuilds on failure)"
    echo "  sudo mdadm --create /dev/md0 --level=5 --raid-devices=3 --spare-devices=1 \\"
    echo "      /dev/sdb /dev/sdc /dev/sdd /dev/sde"
    echo ""
    echo "  RAID level comparison:"
    echo "    Level | Min Disks | Capacity     | Fault Tolerance | Use Case"
    echo "    ------|-----------|--------------|-----------------|------------------"
    echo "    0     | 2         | N * disk     | None            | Scratch/temp data"
    echo "    1     | 2         | 1 * disk     | N-1 disks       | OS, critical data"
    echo "    5     | 3         | (N-1) * disk | 1 disk          | File servers"
    echo "    6     | 4         | (N-2) * disk | 2 disks         | Large arrays"
    echo "    10    | 4         | N/2 * disk   | 1 per mirror    | Databases"
    echo ""
    echo "  Explanation:"
    echo "    --level sets the RAID type; --raid-devices sets the active disk count"
    echo "    --spare-devices adds hot spares that auto-activate on failure"
    echo "    RAID is NOT a backup — it protects against disk failure, not data loss"
    echo ""

    echo "--- Part B: Managing and Monitoring RAID ---"
    echo "Solution:"
    echo "  # Check array status"
    echo "  cat /proc/mdstat                                 # Quick overview"
    echo "  sudo mdadm --detail /dev/md0                     # Detailed info"
    echo ""
    echo "  # Save configuration (CRITICAL — do this after creating arrays)"
    echo "  sudo mdadm --detail --scan | sudo tee -a /etc/mdadm/mdadm.conf"
    echo "  sudo update-initramfs -u                          # Update boot image"
    echo ""
    echo "  # Create filesystem and mount"
    echo "  sudo mkfs.ext4 /dev/md0"
    echo "  sudo mkdir -p /data"
    echo "  sudo mount /dev/md0 /data"
    echo ""
    echo "  # Add to /etc/fstab for persistent mount"
    echo "  echo '/dev/md0  /data  ext4  defaults  0 2' | sudo tee -a /etc/fstab"
    echo ""
    echo "  # Monitor with email alerts"
    echo "  sudo mdadm --monitor --mail=admin@company.com --delay=300 /dev/md0 &"
    echo ""
    echo "  Explanation:"
    echo "    /proc/mdstat shows sync progress and array state in real time"
    echo "    Saving to mdadm.conf is critical — without it, arrays may not reassemble on reboot"
    echo "    update-initramfs ensures the RAID is assembled during early boot"
    echo "    --monitor watches for failures and sends email alerts"
    echo ""

    echo "--- Part C: RAID Failure Recovery ---"
    echo "Solution:"
    echo "  # Simulate a disk failure (for testing only!)"
    echo "  sudo mdadm --manage /dev/md0 --fail /dev/sdc"
    echo ""
    echo "  # Check degraded status"
    echo "  cat /proc/mdstat                                 # Shows [U_] for degraded"
    echo "  sudo mdadm --detail /dev/md0                     # Shows failed disk"
    echo ""
    echo "  # Remove the failed disk"
    echo "  sudo mdadm --manage /dev/md0 --remove /dev/sdc"
    echo ""
    echo "  # Add replacement disk"
    echo "  sudo mdadm --manage /dev/md0 --add /dev/sdk      # New disk"
    echo ""
    echo "  # Watch rebuild progress"
    echo "  watch cat /proc/mdstat"
    echo ""
    echo "  Explanation:"
    echo "    --fail marks a disk as faulty (it's removed from active use)"
    echo "    --remove physically disconnects the failed disk from the array"
    echo "    --add incorporates the replacement; rebuild starts automatically"
    echo "    Rebuild time depends on array size and I/O load"
    echo "    NEVER remove a second disk during rebuild (data loss in RAID 5!)"
    echo ""

    echo "--- Verification ---"
    echo "  cat /proc/mdstat              # All arrays should show [UU] or [UUU]"
    echo "  sudo mdadm --detail /dev/md0  # State should be 'active' or 'clean'"
}

# === Exercise 3: LUKS Disk Encryption ===
# Problem: Set up full disk encryption using LUKS for data-at-rest protection.
exercise_3() {
    echo "=== Exercise 3: LUKS Disk Encryption ==="
    echo ""
    echo "Scenario: Encrypt sensitive data storage on a server to comply with"
    echo "security regulations and protect against physical disk theft."
    echo ""

    echo "--- Part A: Creating a LUKS Encrypted Volume ---"
    echo "Solution:"
    echo "  # Format the disk with LUKS encryption (WARNING: destroys all data!)"
    echo "  sudo cryptsetup luksFormat --type luks2 /dev/sdb"
    echo "  # You will be prompted for a passphrase"
    echo ""
    echo "  # Open (decrypt) the volume"
    echo "  sudo cryptsetup luksOpen /dev/sdb secure-data"
    echo "  # Creates /dev/mapper/secure-data"
    echo ""
    echo "  # Create filesystem on the decrypted device"
    echo "  sudo mkfs.ext4 /dev/mapper/secure-data"
    echo ""
    echo "  # Mount and use"
    echo "  sudo mkdir -p /secure"
    echo "  sudo mount /dev/mapper/secure-data /secure"
    echo ""
    echo "  Explanation:"
    echo "    luksFormat initializes the LUKS header and sets the master key"
    echo "    --type luks2 uses the newer format (better security, more key slots)"
    echo "    luksOpen decrypts the master key and creates a device-mapper device"
    echo "    All reads/writes through /dev/mapper/* are transparently encrypted/decrypted"
    echo "    Performance impact is minimal on modern CPUs with AES-NI instruction support"
    echo ""

    echo "--- Part B: Key Management ---"
    echo "Solution:"
    echo "  # View LUKS header info"
    echo "  sudo cryptsetup luksDump /dev/sdb"
    echo ""
    echo "  # Add a backup passphrase (up to 8 key slots in LUKS2)"
    echo "  sudo cryptsetup luksAddKey /dev/sdb"
    echo "  # Enter existing passphrase, then enter new passphrase"
    echo ""
    echo "  # Add a key file (for automated unlocking)"
    echo "  sudo dd if=/dev/urandom of=/root/luks-keyfile bs=4096 count=1"
    echo "  sudo chmod 400 /root/luks-keyfile"
    echo "  sudo cryptsetup luksAddKey /dev/sdb /root/luks-keyfile"
    echo ""
    echo "  # Remove a key slot"
    echo "  sudo cryptsetup luksRemoveKey /dev/sdb"
    echo "  # Or by slot number:"
    echo "  sudo cryptsetup luksKillSlot /dev/sdb 1"
    echo ""
    echo "  # Backup LUKS header (CRITICAL for disaster recovery)"
    echo "  sudo cryptsetup luksHeaderBackup /dev/sdb --header-backup-file /backup/luks-header.img"
    echo ""
    echo "  Explanation:"
    echo "    LUKS supports multiple key slots (passphrases or key files)"
    echo "    Key files enable automatic unlocking at boot (store securely!)"
    echo "    If the LUKS header is corrupted and there's no backup, ALL data is lost"
    echo "    Always backup the header and store it offline (USB drive in a safe)"
    echo "    luksDump shows key slots, cipher, and hash algorithm"
    echo ""

    echo "--- Part C: Automatic Unlocking at Boot ---"
    echo "Solution:"
    echo "  # /etc/crypttab — maps encrypted devices to names"
    echo "  echo 'secure-data  /dev/sdb  /root/luks-keyfile  luks' | sudo tee -a /etc/crypttab"
    echo ""
    echo "  # /etc/fstab — mount the decrypted device"
    echo "  echo '/dev/mapper/secure-data  /secure  ext4  defaults  0 2' | sudo tee -a /etc/fstab"
    echo ""
    echo "  # Update initramfs to include crypttab settings"
    echo "  sudo update-initramfs -u"
    echo ""
    echo "  # For servers without physical console (no passphrase prompt at boot):"
    echo "  # Use a key file stored on the root filesystem (which itself may be encrypted)"
    echo "  # Or use network-bound disk encryption (NBDE) with clevis + tang server:"
    echo "  sudo clevis luks bind -d /dev/sdb tang '{\"url\":\"http://tang.internal\"}'"
    echo ""
    echo "  Explanation:"
    echo "    crypttab format: name  device  key_file  options"
    echo "    'none' as key_file means prompt for passphrase at boot"
    echo "    A key file path means automatic unlock (no prompt)"
    echo "    NBDE (clevis/tang) provides network-based automatic unlocking"
    echo "    tang server holds a decryption key; server must be on the network to boot"
    echo ""

    echo "--- Part D: Close and Verify ---"
    echo "Solution:"
    echo "  # Unmount and close the encrypted volume"
    echo "  sudo umount /secure"
    echo "  sudo cryptsetup luksClose secure-data"
    echo ""
    echo "  # Verify encryption"
    echo "  sudo cryptsetup isLuks /dev/sdb && echo 'LUKS detected' || echo 'Not LUKS'"
    echo "  sudo cryptsetup luksDump /dev/sdb | grep 'Cipher\\|Key'"
    echo ""
    echo "  # Check CPU support for hardware-accelerated encryption"
    echo "  grep -m1 aes /proc/cpuinfo && echo 'AES-NI supported' || echo 'No AES-NI'"
    echo ""
    echo "  # Benchmark encryption performance"
    echo "  sudo cryptsetup benchmark"
    echo ""
    echo "  Explanation:"
    echo "    luksClose removes the device-mapper entry and flushes encryption keys from memory"
    echo "    AES-NI hardware acceleration makes encryption nearly free on modern CPUs"
    echo "    cryptsetup benchmark shows throughput for different cipher/key-size combinations"
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
echo "All exercises completed!"
