#!/bin/bash
# Exercises for Lesson 26: Troubleshooting Guide
# Topic: Linux
# Solutions to practice problems from the lesson.

# === Exercise 1: Boot Issue ===
# Problem: System boots to emergency mode. Find and resolve the cause.
exercise_1() {
    echo "=== Exercise 1: Emergency Mode Boot Troubleshooting ==="
    echo ""
    echo "Scenario: The system drops into emergency mode instead of normal boot."
    echo "This typically means a critical filesystem or service failed to start."
    echo ""

    echo "--- Step 1: Check error messages ---"
    echo "  journalctl -xb"
    echo ""
    echo "  Flags:"
    echo "    -x = Include explanatory help text for log entries"
    echo "    -b = Show logs from the current boot only"
    echo "  Look for lines with 'error', 'failed', or 'emergency' in red/bold."
    echo ""
    echo "  dmesg | grep -i error"
    echo ""
    echo "  dmesg shows kernel ring buffer messages. Errors here often relate to"
    echo "  hardware, drivers, or filesystem issues detected early in boot."
    echo ""

    echo "--- Step 2: Identify common causes ---"
    echo ""
    echo "  Cause A: /etc/fstab errors (most common)"
    echo "    Symptoms: 'dependency failed' for mount units"
    echo "    Check:"
    echo "      cat /etc/fstab"
    echo "      # Look for:"
    echo "      #   - Incorrect UUIDs (blkid to verify)"
    echo "      #   - Missing devices (drive removed, changed)"
    echo "      #   - Typos in mount points or filesystem types"
    echo ""
    echo "    Fix options:"
    echo "      # Option 1: Fix the UUID"
    echo "      blkid                     # Find correct UUIDs"
    echo "      vi /etc/fstab             # Correct the entry"
    echo ""
    echo "      # Option 2: Add 'nofail' option (allows boot even if mount fails)"
    echo "      # Change: UUID=xxx /data ext4 defaults 0 2"
    echo "      # To:     UUID=xxx /data ext4 defaults,nofail 0 2"
    echo ""
    echo "      # Option 3: Comment out the problematic line"
    echo "      # (prefix with #)"
    echo ""

    echo "  Cause B: Filesystem corruption"
    echo "    Symptoms: 'fsck failed' or 'filesystem is not clean'"
    echo "    Fix:"
    echo "      fsck -y /dev/sda1         # Auto-fix (-y = yes to all)"
    echo "      # CAUTION: Run fsck only on UNMOUNTED filesystems"
    echo "      # In emergency mode, root may be mounted read-only (safe to fsck others)"
    echo ""

    echo "  Cause C: SELinux labeling issues"
    echo "    Symptoms: 'SELinux' mentioned in logs, services denied"
    echo "    Fix:"
    echo "      # Temporarily set permissive to get past boot"
    echo "      setenforce 0"
    echo "      # Then relabel the filesystem"
    echo "      touch /.autorelabel"
    echo "      reboot"
    echo ""

    echo "--- Step 3: After fixing, reboot ---"
    echo "  # Remount root read-write if needed"
    echo "  mount -o remount,rw /"
    echo "  # Make your fixes, then"
    echo "  reboot"
    echo ""

    echo "--- Step 4: Verify normal boot ---"
    echo "  systemctl --failed             # Check for failed units"
    echo "  journalctl -p err -b           # Check for error messages"
    echo "  mount | column -t              # Verify all filesystems mounted"
}

# === Exercise 2: Disk Space ===
# Problem: /var partition is 100% full. Find the cause and resolve it.
exercise_2() {
    echo "=== Exercise 2: /var Partition Full (100%) ==="
    echo ""
    echo "Scenario: Disk full on /var causes services to fail (logs can't write,"
    echo "databases can't operate, package manager breaks)."
    echo ""

    echo "--- Step 1: Confirm the problem ---"
    echo "  df -h /var"
    echo ""
    # Safe to run on any system
    if df -h /var &>/dev/null; then
        echo "  Current /var usage:"
        df -h /var 2>/dev/null | tail -1
    fi
    echo ""

    echo "--- Step 2: Find the largest directories ---"
    echo "  du -h --max-depth=1 /var | sort -hr | head -10"
    echo ""
    echo "  Flags:"
    echo "    --max-depth=1   # Only show immediate subdirectories"
    echo "    sort -hr        # Sort by human-readable sizes, reverse (largest first)"
    echo ""
    echo "  Common space hogs in /var:"
    echo "    /var/log        - Log files (syslog, application logs)"
    echo "    /var/cache      - Package manager cache (apt/yum)"
    echo "    /var/lib/docker - Docker images, containers, volumes"
    echo "    /var/lib/mysql  - Database data"
    echo "    /var/mail       - Email spool"
    echo ""

    echo "--- Step 3: Find large individual files ---"
    echo "  find /var -type f -size +100M -exec ls -lh {} \\;"
    echo ""
    echo "  This finds files larger than 100MB. Adjust the threshold as needed."
    echo ""

    echo "--- Step 4: Check specific common causes ---"
    echo "  du -sh /var/log"
    echo "  du -sh /var/cache"
    echo "  du -sh /var/lib/docker     # If using Docker"
    echo ""

    echo "--- Step 5: Clean up (choose appropriate method) ---"
    echo ""
    echo "  Method A: Truncate systemd journal"
    echo "    journalctl --vacuum-size=100M    # Keep only 100MB of logs"
    echo "    journalctl --vacuum-time=7d      # Keep only 7 days of logs"
    echo ""
    echo "  Method B: Clean old compressed logs"
    echo "    find /var/log -name '*.gz' -mtime +7 -delete"
    echo "    find /var/log -name '*.1' -mtime +7 -delete"
    echo ""
    echo "  Method C: Truncate a specific large log (don't delete while in use!)"
    echo "    truncate -s 0 /var/log/large-file.log"
    echo "    # truncate is safe because it keeps the inode (file handle) intact"
    echo "    # 'rm' on an open file frees the name but NOT the space until process exits"
    echo ""
    echo "  Method D: Clean package cache"
    echo "    sudo apt-get clean              # Debian/Ubuntu"
    echo "    sudo yum clean all              # RHEL/CentOS"
    echo ""
    echo "  Method E: Clean Docker"
    echo "    docker system prune -a --volumes  # Remove unused images, containers, volumes"
    echo ""

    echo "--- Step 6: Check for deleted-but-open files ---"
    echo "  lsof +L1 | grep /var"
    echo ""
    echo "  Why: When you 'rm' a file that a process still has open, the space is NOT freed"
    echo "  until the process closes the file handle. lsof +L1 shows files with 0 links"
    echo "  (deleted) that are still held open."
    echo ""
    echo "  Fix: Restart the offending service to release the file handle."
    echo "    systemctl restart <service-name>"
    echo ""

    echo "--- Prevention ---"
    echo "  - Configure logrotate for all applications"
    echo "  - Set up monitoring alerts at 80% usage"
    echo "  - Use separate partitions for /var, /var/log, /var/lib/docker"
    echo "  - Set journal size limit: /etc/systemd/journald.conf -> SystemMaxUse=500M"
}

# === Exercise 3: Network Connection ===
# Problem: Cannot access external websites. Diagnose step by step.
exercise_3() {
    echo "=== Exercise 3: Network Connectivity Troubleshooting ==="
    echo ""
    echo "Scenario: Cannot access external websites. Systematic layer-by-layer diagnosis."
    echo ""
    echo "Approach: Follow the OSI model bottom-up (physical -> application)."
    echo ""

    echo "--- Step 1: Check interface status (Layer 1-2) ---"
    echo "  ip addr show"
    echo "  ip link show"
    echo ""
    echo "  Check for:"
    echo "    - Interface is UP (not DOWN)"
    echo "    - Has an IP address assigned"
    echo "    - 'NO-CARRIER' means physical link is down (cable disconnected)"
    echo ""
    # Safe read-only demonstration
    echo "  Current interfaces:"
    ip addr show 2>/dev/null | grep -E "^[0-9]+:|inet " | head -10
    echo ""

    echo "--- Step 2: Check default gateway (Layer 3) ---"
    echo "  ip route show"
    echo "  ping -c 3 <gateway-ip>"
    echo ""
    echo "  Check: Is there a 'default via X.X.X.X' route?"
    echo "  If no default route: sudo ip route add default via <gateway-ip>"
    echo ""
    echo "  If gateway is unreachable:"
    echo "    - Check physical connection (cable, switch, VLAN)"
    echo "    - Verify gateway IP is correct"
    echo "    - Ensure gateway is on the same subnet"
    echo ""

    echo "--- Step 3: Test external IP connectivity (Layer 3) ---"
    echo "  ping -c 3 8.8.8.8"
    echo ""
    echo "  If this WORKS but websites DON'T -> it's a DNS problem (go to Step 4)"
    echo "  If this FAILS -> routing or firewall issue (go to Step 5)"
    echo ""

    echo "--- Step 4: Check DNS resolution (Layer 7) ---"
    echo "  nslookup google.com"
    echo "  # or: dig google.com"
    echo "  cat /etc/resolv.conf"
    echo ""
    echo "  If DNS fails:"
    echo "    Fix resolv.conf:"
    echo "      echo 'nameserver 8.8.8.8' | sudo tee /etc/resolv.conf"
    echo "    Or for systemd-resolved:"
    echo "      resolvectl status"
    echo "      sudo systemd-resolve --set-dns=8.8.8.8 --interface=eth0"
    echo ""

    echo "--- Step 5: Check firewall rules ---"
    echo "  iptables -L -n               # List iptables rules"
    echo "  nft list ruleset             # List nftables rules"
    echo "  firewall-cmd --list-all      # firewalld (RHEL/CentOS)"
    echo ""
    echo "  Look for DROP/REJECT rules on OUTPUT chain that block outbound traffic."
    echo "  Common issue: firewall blocking outbound DNS (port 53) or HTTPS (port 443)."
    echo ""

    echo "--- Step 6: Test specific port connectivity ---"
    echo "  nc -zv google.com 443        # Test TCP connection to HTTPS port"
    echo "  curl -I https://google.com   # Test full HTTP connection"
    echo ""
    echo "  If nc succeeds but curl fails -> possible TLS/proxy issue"
    echo "  If nc fails on 443 but ping works -> port blocked by firewall"
    echo ""

    echo "--- Step 7: Trace the routing path ---"
    echo "  traceroute google.com"
    echo "  # or: mtr google.com    (combines ping + traceroute, real-time)"
    echo ""
    echo "  Shows each hop between you and the destination."
    echo "  '* * *' at a hop means that hop is blocking ICMP (may be normal)"
    echo "  If trace stops at your gateway -> upstream routing problem"
    echo ""

    echo "--- Diagnosis Summary ---"
    echo ""
    echo "  Symptom                      | Likely Cause           | Fix"
    echo "  -----------------------------|------------------------|-----"
    echo "  No IP address                | DHCP or static config  | dhclient / ip addr add"
    echo "  Gateway unreachable          | Cable/switch/VLAN      | Physical check"
    echo "  8.8.8.8 unreachable          | Router/firewall        | Check routing + fw rules"
    echo "  IP works, DNS fails          | DNS misconfiguration   | Fix /etc/resolv.conf"
    echo "  DNS works, HTTP fails        | Proxy/firewall/TLS     | Check proxy_env, certs"
    echo "  Intermittent connectivity    | MTU/packet loss        | ping -s 1400, tc stats"
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
echo "All exercises completed!"
