# dvc.yaml — ML Pipeline Definition for DVC
#
# Stages:
#   prepare   → Split raw data into train/test
#   featurize → Engineer features from prepared data
#   train     → Train model with specified hyperparameters
#   evaluate  → Evaluate model on test set, output metrics + plots
#
# Run: dvc repro
# Compare: dvc metrics diff HEAD~1
# Experiments: dvc exp run --set-param train.n_estimators=500

stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/raw/dataset.csv
    params:
      - prepare.split_ratio
      - prepare.seed
      - prepare.stratify
    outs:
      - data/prepared/train.csv
      - data/prepared/test.csv
    metrics:
      - metrics/data_stats.json:
          cache: false

  featurize:
    cmd: python src/featurize.py
    deps:
      - src/featurize.py
      - data/prepared/train.csv
      - data/prepared/test.csv
    params:
      - featurize.max_features
      - featurize.ngram_range
      - featurize.use_tfidf
      - featurize.numerical_transforms
    outs:
      - data/features/X_train.csv
      - data/features/X_test.csv
      - data/features/y_train.csv
      - data/features/y_test.csv
      - models/feature_pipeline.pkl

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/features/X_train.csv
      - data/features/y_train.csv
    params:
      - train.model_type
      - train.n_estimators
      - train.learning_rate
      - train.max_depth
      - train.min_samples_leaf
      - train.subsample
    outs:
      - models/model.pkl
    metrics:
      - metrics/train_metrics.json:
          cache: false
    plots:
      - plots/feature_importance.csv:
          x: feature
          y: importance

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pkl
      - data/features/X_test.csv
      - data/features/y_test.csv
    metrics:
      - metrics/eval_metrics.json:
          cache: false
    plots:
      - plots/roc_curve.csv:
          x: fpr
          y: tpr
      - plots/precision_recall.csv:
          x: recall
          y: precision
      - plots/confusion_matrix.csv:
          x: predicted
          y: actual
          template: confusion
