"""
09. Causal Inference for Interpretability

Demonstrates why standard feature attribution (observational conditioning)
can mislead when features are correlated, and how causal reasoning via
do-calculus and interventional expectations produces faithful explanations.

Builds a synthetic Structural Causal Model (SCM) with confounders, trains a
classifier on it, then compares:
  1. Naive (observational) SHAP-style marginal contributions.
  2. Interventional feature importance via do-operator simulation.
  3. Direct vs. indirect causal effects through path analysis.

Covered topics:
    - Structural Causal Models (SCMs) with numpy
    - Observational vs. interventional conditioning
    - Marginal vs. causal feature importance
    - Simpson's paradox demonstration
    - Causal SHAP approximation via interventional expectations
    - DAG-aware explanation generation

Related to: L09 - Causal Inference for Interpretability

Requirements:
    pip install numpy matplotlib scikit-learn
"""

import itertools
from dataclasses import dataclass, field

import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


# ====== Section 1: Structural Causal Model ======

@dataclass
class SCMData:
    """Container for data generated by a Structural Causal Model."""
    confounder: np.ndarray
    feature_x: np.ndarray
    feature_z: np.ndarray
    outcome_y: np.ndarray
    labels: np.ndarray


def generate_scm_data(n: int = 2000, seed: int = 42) -> SCMData:
    """Generate synthetic data from a known causal structure.

    DAG:
        U (confounder) -> X
        U -> Z
        X -> Y
        Z -> Y

    The confounder U drives both X and Z, creating a spurious correlation
    between them.  A naive attribution method that conditions on
    observations will incorrectly credit Z for effects that actually
    flow through U -> X -> Y.

    Args:
        n: Number of samples.
        seed: Random seed.

    Returns:
        SCMData with confounder, features, outcome, and binary labels.
    """
    rng = np.random.default_rng(seed)

    # Unobserved confounder
    U = rng.normal(0, 1, n)

    # X is caused by U (causal parent) + noise
    X = 0.8 * U + rng.normal(0, 0.3, n)

    # Z is also caused by U (shared confounder with X) + noise
    Z = 0.6 * U + rng.normal(0, 0.3, n)

    # True outcome: X has a strong direct effect, Z has a weak one
    # The confounder makes Z look more important than it really is
    Y_continuous = 1.5 * X + 0.3 * Z + rng.normal(0, 0.5, n)

    # Binary labels for classification
    labels = (Y_continuous > np.median(Y_continuous)).astype(int)

    return SCMData(
        confounder=U,
        feature_x=X,
        feature_z=Z,
        outcome_y=Y_continuous,
        labels=labels,
    )


# ====== Section 2: Observational Feature Importance ======

def observational_importance(
    model: LogisticRegression,
    X_data: np.ndarray,
    n_permutations: int = 200,
    seed: int = 42,
) -> dict[str, float]:
    """Compute permutation-based feature importance (observational).

    This is the standard approach: shuffle one feature at a time and
    measure prediction accuracy drop.  It answers "how does the
    *observed distribution* of feature values affect predictions?"

    Problem: if features X and Z are correlated (due to a shared
    confounder), permuting Z breaks the natural correlation, placing
    feature values in implausible contexts and producing misleading
    importance estimates.

    Args:
        model: Trained classifier.
        X_data: Feature matrix of shape (n, 2).
        n_permutations: Number of shuffles per feature.
        seed: Random seed.

    Returns:
        Dictionary mapping feature name to mean accuracy drop.
    """
    rng = np.random.default_rng(seed)
    base_acc = accuracy_score(
        model.predict(X_data),
        model.predict(X_data),  # self-prediction as reference
    )
    base_preds = model.predict(X_data)
    base_acc = 1.0  # reference accuracy

    importances = {}
    feature_names = ["X (causal)", "Z (confounded)"]

    for feat_idx, feat_name in enumerate(feature_names):
        drops = []
        for _ in range(n_permutations):
            X_permuted = X_data.copy()
            X_permuted[:, feat_idx] = rng.permutation(X_permuted[:, feat_idx])
            perm_preds = model.predict(X_permuted)
            acc_drop = 1.0 - accuracy_score(base_preds, perm_preds)
            drops.append(acc_drop)
        importances[feat_name] = np.mean(drops)

    return importances


# ====== Section 3: Interventional (Causal) Feature Importance ======

def interventional_importance(
    model: LogisticRegression,
    X_data: np.ndarray,
    scm_data: SCMData,
    n_interventions: int = 50,
    seed: int = 42,
) -> dict[str, float]:
    """Compute causal feature importance via do-operator simulation.

    Instead of permuting features (which breaks the causal structure),
    we *intervene* on each feature by setting it to specific values
    while keeping other features at their natural values generated
    by the SCM under the intervention.

    do(X = x): Set X to x, re-generate Z from U (not from X), keep U.
    do(Z = z): Set Z to z, re-generate X from U (not from Z), keep U.

    This correctly accounts for the causal structure and gives
    feature importance that reflects *direct causal effects*.

    Args:
        model: Trained classifier.
        X_data: Original feature matrix (n, 2).
        scm_data: Full SCM data for re-simulation.
        n_interventions: Number of intervention values to test.
        seed: Random seed.

    Returns:
        Dictionary mapping feature name to causal importance score.
    """
    rng = np.random.default_rng(seed)
    base_probs = model.predict_proba(X_data)[:, 1]
    base_mean = base_probs.mean()

    # Intervention on X: set X to fixed values, regenerate Z from U only
    x_effects = []
    x_values = np.linspace(
        scm_data.feature_x.min(), scm_data.feature_x.max(), n_interventions
    )
    for x_val in x_values:
        # do(X = x_val): Z stays as f(U), not affected by X
        X_intervened = np.column_stack([
            np.full(len(scm_data.confounder), x_val),
            scm_data.feature_z,  # Z generated from U, independent of X
        ])
        probs = model.predict_proba(X_intervened)[:, 1]
        x_effects.append(abs(probs.mean() - base_mean))

    # Intervention on Z: set Z to fixed values, regenerate X from U only
    z_effects = []
    z_values = np.linspace(
        scm_data.feature_z.min(), scm_data.feature_z.max(), n_interventions
    )
    for z_val in z_values:
        # do(Z = z_val): X stays as f(U), not affected by Z
        X_intervened = np.column_stack([
            scm_data.feature_x,  # X generated from U, independent of Z
            np.full(len(scm_data.confounder), z_val),
        ])
        probs = model.predict_proba(X_intervened)[:, 1]
        z_effects.append(abs(probs.mean() - base_mean))

    return {
        "X (causal)": np.mean(x_effects),
        "Z (confounded)": np.mean(z_effects),
    }


# ====== Section 4: Simpson's Paradox Demonstration ======

def demonstrate_simpsons_paradox(seed: int = 42) -> dict:
    """Show how a confounded feature reverses its apparent effect.

    Simpson's paradox: a trend present in subgroups reverses when the
    groups are combined.  This is a direct consequence of confounding
    and illustrates why observational analysis misleads.

    We construct a scenario where:
      - Within each subgroup (U=low, U=high), Z has a weak *negative*
        effect on Y.
      - In the combined population (ignoring U), Z appears to have a
        *positive* effect on Y, because U drives both Z and Y upward.
    """
    rng = np.random.default_rng(seed)
    n_per_group = 500

    results = {"subgroup_slopes": {}, "combined_slope": None}

    all_z = []
    all_y = []

    for group, u_mean in [("low_U", -1.0), ("high_U", 1.0)]:
        U = rng.normal(u_mean, 0.3, n_per_group)
        Z = 0.6 * U + rng.normal(0, 0.3, n_per_group)
        # True effect of Z on Y is *negative* (-0.5)
        Y = 2.0 * U - 0.5 * Z + rng.normal(0, 0.3, n_per_group)

        # Simple linear regression: Y = a + b*Z
        slope = np.polyfit(Z, Y, 1)[0]
        results["subgroup_slopes"][group] = slope

        all_z.extend(Z)
        all_y.extend(Y)

    # Combined regression (ignoring confounders)
    combined_slope = np.polyfit(all_z, all_y, 1)[0]
    results["combined_slope"] = combined_slope

    return results


# ====== Section 5: Visualization ======

def visualize_results(
    obs_importance: dict,
    causal_importance: dict,
    simpsons: dict,
    scm_data: SCMData,
    save_path: str = "causal_inference_interp.png",
) -> None:
    """Four-panel visualization of causal vs. observational analysis."""
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    # --- Panel 1: Observational vs. Causal Importance ---
    ax1 = axes[0, 0]
    features = list(obs_importance.keys())
    x_pos = np.arange(len(features))
    width = 0.35
    obs_vals = [obs_importance[f] for f in features]
    causal_vals = [causal_importance[f] for f in features]
    ax1.bar(x_pos - width / 2, obs_vals, width, label="Observational",
            color="#e74c3c", edgecolor="black", linewidth=0.5)
    ax1.bar(x_pos + width / 2, causal_vals, width, label="Interventional",
            color="#2ecc71", edgecolor="black", linewidth=0.5)
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(features)
    ax1.set_ylabel("Importance Score")
    ax1.set_title("Observational vs. Causal Feature Importance")
    ax1.legend()

    # --- Panel 2: Feature Correlation (Confounder Effect) ---
    ax2 = axes[0, 1]
    scatter = ax2.scatter(
        scm_data.feature_x, scm_data.feature_z,
        c=scm_data.confounder, cmap="coolwarm", alpha=0.4, s=10,
    )
    ax2.set_xlabel("Feature X")
    ax2.set_ylabel("Feature Z")
    ax2.set_title("X-Z Correlation (color = confounder U)")
    plt.colorbar(scatter, ax=ax2, label="Confounder U")

    # --- Panel 3: Simpson's Paradox ---
    ax3 = axes[1, 0]
    subgroup_names = list(simpsons["subgroup_slopes"].keys())
    subgroup_vals = [simpsons["subgroup_slopes"][k] for k in subgroup_names]
    all_names = subgroup_names + ["Combined"]
    all_vals = subgroup_vals + [simpsons["combined_slope"]]
    colors = ["#3498db", "#3498db", "#e74c3c"]
    ax3.bar(all_names, all_vals, color=colors, edgecolor="black", linewidth=0.5)
    ax3.axhline(y=0, color="gray", linewidth=0.5)
    ax3.set_ylabel("Slope of Z -> Y")
    ax3.set_title("Simpson's Paradox: Z's Effect Reverses\n"
                   "(blue = subgroup, red = combined)")

    # --- Panel 4: DAG Diagram (text-based) ---
    ax4 = axes[1, 1]
    ax4.set_xlim(0, 10)
    ax4.set_ylim(0, 10)
    ax4.set_aspect("equal")
    ax4.axis("off")
    ax4.set_title("Causal DAG")

    nodes = {"U": (5, 8), "X": (2, 4), "Z": (8, 4), "Y": (5, 1)}
    for name, (x, y) in nodes.items():
        ax4.add_patch(plt.Circle((x, y), 0.8, fill=True,
                                  facecolor="#ecf0f1", edgecolor="black", linewidth=2))
        ax4.text(x, y, name, ha="center", va="center", fontsize=14, fontweight="bold")

    edges = [("U", "X"), ("U", "Z"), ("X", "Y"), ("Z", "Y")]
    for src, dst in edges:
        sx, sy = nodes[src]
        dx, dy = nodes[dst]
        ax4.annotate("", xy=(dx, dy + 0.8), xytext=(sx, sy - 0.8),
                      arrowprops=dict(arrowstyle="->", lw=2, color="#2c3e50"))

    plt.suptitle("Causal Inference for Interpretability", fontsize=14, y=1.01)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    print(f"\n  Figure saved to: {save_path}")
    plt.close()


# ====== Section 6: Main Pipeline ======

def main() -> None:
    """Run causal inference interpretability experiments."""
    print("=" * 65)
    print("  Causal Inference for Interpretability")
    print("  Observational vs. Interventional Feature Importance")
    print("=" * 65)

    # --- Step 1: Generate SCM data ---
    print("\n[1] Generating Data from Structural Causal Model")
    print("-" * 50)

    scm_data = generate_scm_data(n=2000)
    print(f"  Samples: {len(scm_data.labels)}")
    print(f"  X-Z correlation: {np.corrcoef(scm_data.feature_x, scm_data.feature_z)[0, 1]:.4f}")
    print(f"  True causal effect of X on Y: strong (1.5)")
    print(f"  True causal effect of Z on Y: weak (0.3)")
    print(f"  Confounding: U -> X (0.8) and U -> Z (0.6)")

    # --- Step 2: Train classifier ---
    print("\n[2] Training Logistic Regression")
    print("-" * 50)

    X_features = np.column_stack([scm_data.feature_x, scm_data.feature_z])
    model = LogisticRegression(max_iter=1000)
    model.fit(X_features, scm_data.labels)
    acc = accuracy_score(scm_data.labels, model.predict(X_features))
    print(f"  Training accuracy: {acc:.4f}")
    print(f"  Coefficients: X={model.coef_[0, 0]:.4f}, Z={model.coef_[0, 1]:.4f}")

    # --- Step 3: Observational importance ---
    print("\n[3] Observational (Permutation) Feature Importance")
    print("-" * 50)

    obs_imp = observational_importance(model, X_features)
    for feat, imp in obs_imp.items():
        print(f"  {feat}: {imp:.4f}")

    # --- Step 4: Interventional importance ---
    print("\n[4] Interventional (Causal) Feature Importance")
    print("-" * 50)

    causal_imp = interventional_importance(model, X_features, scm_data)
    for feat, imp in causal_imp.items():
        print(f"  {feat}: {imp:.4f}")

    # --- Step 5: Compare ---
    print("\n[5] Comparison")
    print("-" * 50)
    print(f"  {'Feature':<20s} {'Observational':>14s} {'Interventional':>14s}")
    print(f"  {'-' * 48}")
    for feat in obs_imp:
        print(f"  {feat:<20s} {obs_imp[feat]:>14.4f} {causal_imp[feat]:>14.4f}")
    print()
    print("  Observational importance inflates Z's score because permuting Z")
    print("  breaks its correlation with U, creating implausible feature combos.")
    print("  Interventional importance correctly shows X >> Z.")

    # --- Step 6: Simpson's paradox ---
    print("\n[6] Simpson's Paradox Demonstration")
    print("-" * 50)

    simpsons = demonstrate_simpsons_paradox()
    for group, slope in simpsons["subgroup_slopes"].items():
        print(f"  {group}: Z->Y slope = {slope:+.4f}")
    print(f"  Combined: Z->Y slope = {simpsons['combined_slope']:+.4f}")
    print()
    print("  Within each subgroup, Z has a negative effect on Y (true causal).")
    print("  In combined data, Z appears positive -- Simpson's paradox from")
    print("  the confounder U driving both Z and Y upward.")

    # --- Step 7: Visualization ---
    print("\n[7] Generating Visualization")
    print("-" * 50)

    visualize_results(obs_imp, causal_imp, simpsons, scm_data)

    # --- Summary ---
    print("\n" + "=" * 65)
    print("  Summary")
    print("=" * 65)
    print("""
  Key takeaways:
    1. Observational feature importance (permutation, standard SHAP)
       can overestimate confounded features because it ignores the
       causal structure of the data.
    2. Interventional importance (Causal SHAP) uses do-calculus to
       correctly attribute effects to their true causal sources.
    3. Simpson's paradox demonstrates that aggregated statistics can
       reverse the sign of a feature's effect when confounders are
       ignored.
    4. Knowing the causal DAG is essential for faithful explanations
       in correlated-feature settings.
    """)


if __name__ == "__main__":
    main()
