# dbt source definitions — points to the Bronze layer tables.

version: 2

sources:
  - name: bronze
    description: "Bronze layer: raw data extracted from source systems"
    schema: public
    tables:
      - name: orders
        description: "Raw orders from ecommerce source"
      - name: customers
        description: "Customer master data"
      - name: products
        description: "Product catalog"
