"""
Exercises for Lesson 20: LLVM IR Introduction
Topic: Compiler_Design

Solutions to practice problems from the lesson.
Demonstrates generating LLVM IR using llvmlite.
"""


# === Exercise 1: Read and Annotate IR ===

def exercise_1():
    """Annotate LLVM IR instructions for a simple function."""
    print("Exercise 1: Annotated LLVM IR for abs(int x)")
    print()
    ir = """
define i32 @abs(i32 %x) {            ; Function: int abs(int x)
entry:
  %cmp = icmp slt i32 %x, 0          ; Compare: x < 0 (signed)
  br i1 %cmp, label %neg, label %pos ; Branch based on comparison

neg:                                   ; x is negative
  %negx = sub i32 0, %x              ; Compute 0 - x = -x
  br label %done                      ; Jump to merge

pos:                                   ; x is non-negative
  br label %done                      ; Jump to merge

done:                                  ; Merge point
  %result = phi i32 [%negx, %neg], [%x, %pos]  ; Select value
  ret i32 %result                     ; Return result
}
""".strip()
    print(ir)
    print()


# === Exercise 2: GCD in LLVM IR ===

def exercise_2():
    """Write LLVM IR for GCD using a loop."""
    print("Exercise 2: GCD in LLVM IR")
    print()
    ir = """
define i32 @gcd(i32 %a, i32 %b) {
entry:
  br label %loop

loop:
  %x = phi i32 [%a, %entry], [%y, %body]
  %y = phi i32 [%b, %entry], [%rem, %body]
  %done = icmp eq i32 %y, 0
  br i1 %done, label %exit, label %body

body:
  %rem = srem i32 %x, %y
  br label %loop

exit:
  ret i32 %x
}
""".strip()
    print(ir)
    print()


# === Exercise 3: Fibonacci with llvmlite ===

def exercise_3():
    """Generate iterative Fibonacci IR (pseudocode, no llvmlite dependency)."""
    print("Exercise 3: Fibonacci IR (generated by llvmlite)")
    print()
    ir = """
define i32 @fibonacci(i32 %n) {
entry:
  br label %loop

loop:
  %i = phi i32 [0, %entry], [%next_i, %loop]
  %a = phi i32 [0, %entry], [%b, %loop]
  %b = phi i32 [1, %entry], [%sum, %loop]
  %sum = add i32 %a, %b
  %next_i = add i32 %i, 1
  %cond = icmp slt i32 %next_i, %n
  br i1 %cond, label %loop, label %exit

exit:
  ret i32 %b
}
""".strip()
    print(ir)
    print()


# === Exercise 4: Struct Access ===

def exercise_4():
    """LLVM IR for struct creation and field access."""
    print("Exercise 4: Struct Access")
    print()
    ir = """
%struct.Point = type { i32, i32, i32 }

define i32 @sum_point() {
entry:
  %p = alloca %struct.Point
  ; Store x=10, y=20, z=30
  %x_ptr = getelementptr %struct.Point, ptr %p, i64 0, i32 0
  store i32 10, ptr %x_ptr
  %y_ptr = getelementptr %struct.Point, ptr %p, i64 0, i32 1
  store i32 20, ptr %y_ptr
  %z_ptr = getelementptr %struct.Point, ptr %p, i64 0, i32 2
  store i32 30, ptr %z_ptr

  ; Read and sum
  %x = load i32, ptr %x_ptr
  %y = load i32, ptr %y_ptr
  %z = load i32, ptr %z_ptr
  %xy = add i32 %x, %y
  %xyz = add i32 %xy, %z
  ret i32 %xyz           ; returns 60
}
""".strip()
    print(ir)
    print()


# === Exercise 5: Array Sum ===

def exercise_5():
    """LLVM IR for summing an i32 array."""
    print("Exercise 5: Array Sum")
    print()
    ir = """
define i32 @array_sum(ptr %arr, i32 %len) {
entry:
  br label %loop

loop:
  %i = phi i32 [0, %entry], [%next_i, %loop]
  %sum = phi i32 [0, %entry], [%new_sum, %loop]
  %elem_ptr = getelementptr i32, ptr %arr, i32 %i
  %elem = load i32, ptr %elem_ptr
  %new_sum = add i32 %sum, %elem
  %next_i = add i32 %i, 1
  %cond = icmp slt i32 %next_i, %len
  br i1 %cond, label %loop, label %exit

exit:
  ret i32 %new_sum
}
""".strip()
    print(ir)
    print()


def main():
    exercises = [exercise_1, exercise_2, exercise_3, exercise_4, exercise_5]
    for i, ex in enumerate(exercises, 1):
        print(f"{'=' * 60}")
        print(f"Exercise {i}")
        print(f"{'=' * 60}")
        ex()


if __name__ == "__main__":
    main()
