"""
Feast FeatureView definitions for the churn prediction project.

Adapted from MLOps Lesson 11 (Feature Stores) and Lesson 12 (Practical Project).
Reads from a local Parquet file (FileSource) instead of S3/BigQuery.
"""

from datetime import timedelta

from feast import FeatureView, Field, FileSource
from feast.types import Float64, Int64, String

from entities import user

# Data source: local Parquet generated by generate_churn_data.py
churn_source = FileSource(
    path="data/churn.parquet",
    timestamp_field="event_timestamp",
)

# Feature view: user behavioral features
user_features = FeatureView(
    name="user_features",
    entities=[user],
    ttl=timedelta(days=365),
    schema=[
        Field(name="age", dtype=Int64),
        Field(name="tenure_months", dtype=Int64),
        Field(name="total_purchases", dtype=Int64),
        Field(name="avg_purchase_amount", dtype=Float64),
        Field(name="customer_segment", dtype=String),
        Field(name="days_since_last_purchase", dtype=Int64),
        Field(name="support_tickets", dtype=Int64),
    ],
    source=churn_source,
    online=True,
)
