"""
Exercises for Lesson 24: RLHF Deep Dive
Topic: Reinforcement_Learning
Solutions to practice problems from the lesson.
"""

import numpy as np


def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-np.clip(x, -50, 50)))


def exercise_1():
    """
    Exercise 1: RLHF Pipeline Components

    Describe all three stages of RLHF and their objectives.
    """
    print("RLHF Pipeline Components:")
    print("=" * 60)

    stages = [
        (
            "Stage 1: Supervised Fine-Tuning (SFT)",
            "Objective: Maximize log P(y | x) over high-quality demonstrations",
            "Data: Curated (prompt, response) pairs from human labelers",
            "Output: SFT model π_SFT that produces coherent, helpful text",
            "Purpose: Give the model a good starting point — the base LLM\n"
            "         trained on web data needs to be steered toward\n"
            "         instruction-following before RL fine-tuning."
        ),
        (
            "Stage 2: Reward Model Training",
            "Objective: Learn R_θ(x, y) from pairwise comparisons",
            "Data: (prompt, y_chosen, y_rejected) triplets",
            "Loss: -E[log σ(R(x, y_w) - R(x, y_l))]  [Bradley-Terry model]",
            "Output: Reward model that scores response quality"
        ),
        (
            "Stage 3: RL Fine-Tuning (PPO)",
            "Objective: max_π E[R(x,y)] - β*KL(π || π_SFT)",
            "Data: Generated by policy, scored by reward model",
            "Output: Fine-tuned policy π_RL aligned with human preferences",
            "KL term prevents 'reward hacking': policy staying near SFT prevents\n"
            "         degenerate outputs that fool the reward model."
        ),
    ]

    for name, obj, data, loss, notes in stages:
        print(f"\n  {name}")
        print(f"    Objective: {obj}")
        print(f"    Data:      {data}")
        print(f"    Loss/Output: {loss}")
        print(f"    Notes:     {notes}")


def exercise_2():
    """
    Exercise 2: Reward Model — Bradley-Terry Model

    Implement and verify the Bradley-Terry pairwise preference model.
    """
    print("\nBradley-Terry Preference Model:")
    print("=" * 60)

    np.random.seed(42)

    # Simulated responses to 3 prompts, each with 2 feature dimensions:
    # [helpfulness, harmlessness]
    true_weights = np.array([3.0, 2.0])  # true reward weights

    def sample_response():
        return np.random.uniform(0, 1, 2)

    # Collect 500 comparison pairs
    data = []
    for _ in range(500):
        phi_a = sample_response()
        phi_b = sample_response()
        r_a = np.dot(true_weights, phi_a) + np.random.randn() * 0.2
        r_b = np.dot(true_weights, phi_b)
        data.append((phi_a, phi_b, r_a > r_b))

    # Train reward model
    w = np.zeros(2)
    for epoch in range(300):
        grad = np.zeros(2)
        for phi_a, phi_b, pref_a in data:
            diff = phi_a - phi_b
            logit = np.dot(w, diff)
            p = sigmoid(logit)
            grad += (int(pref_a) - p) * diff
        w += 0.05 * grad / len(data)

    print(f"\n  True weights:    {true_weights}")
    print(f"  Learned weights: {w.round(3)}")

    # Normalize for direction comparison
    w_norm = w / (np.linalg.norm(w) + 1e-10)
    tw_norm = true_weights / np.linalg.norm(true_weights)
    cos_sim = np.dot(w_norm, tw_norm)
    print(f"  Cosine similarity: {cos_sim:.4f}")

    # Accuracy
    correct = sum(
        1 for phi_a, phi_b, pref in data
        if (np.dot(w, phi_a) > np.dot(w, phi_b)) == pref
    )
    print(f"  Comparison accuracy: {correct/len(data):.1%}")
    print()
    print("  Bradley-Terry assumption:")
    print("  P(y_A > y_B) = sigma(r(y_A) - r(y_B))")
    print("  Learns scalar reward from binary comparisons.")


def exercise_3():
    """
    Exercise 3: KL Divergence Penalty — Reward Hacking Prevention

    Demonstrate how the KL penalty controls reward hacking.
    """
    print("\nKL Penalty Prevents Reward Hacking:")
    print("=" * 60)

    np.random.seed(0)
    n_actions = 8
    pi_ref = np.ones(n_actions) / n_actions  # uniform reference

    # Hacked reward: massive reward for action 0 only
    def reward(action):
        return 20.0 if action == 0 else 0.5

    def kl(p, q):
        mask = p > 1e-12
        return np.sum(p[mask] * np.log(p[mask] / q[mask]))

    def optimize(beta, n_iter=300, lr=0.05):
        logits = np.zeros(n_actions)
        for _ in range(n_iter):
            exp_l = np.exp(logits - np.max(logits))
            pi = exp_l / exp_l.sum()
            for i in range(n_actions):
                e_r = sum(pi[j] * reward(j) for j in range(n_actions))
                adv = reward(i) - e_r - beta * (np.log(pi[i]+1e-10) - np.log(pi_ref[i]+1e-10))
                logits[i] += lr * pi[i] * adv
        exp_l = np.exp(logits - np.max(logits))
        return exp_l / exp_l.sum()

    print(f"\n  Reward: action 0 -> 20, others -> 0.5")
    print(f"  Reference: uniform over {n_actions} actions")
    print()
    print(f"  {'Beta':>6} | {'P(a=0)':>8} | {'E[R]':>7} | {'KL':>8} | {'Objective':>12}")
    print("  " + "-" * 52)

    for beta in [0.0, 0.1, 0.5, 1.0, 5.0]:
        pi = optimize(beta)
        e_r = sum(pi[a] * reward(a) for a in range(n_actions))
        kl_val = kl(pi, pi_ref)
        obj = e_r - beta * kl_val
        print(f"  {beta:>6.1f} | {pi[0]:>8.4f} | {e_r:>7.3f} | {kl_val:>8.4f} | {obj:>12.4f}")

    print()
    print("  Without KL (beta=0): policy concentrates entirely on action 0 (hacked).")
    print("  With large beta: policy stays close to reference (diverse responses).")
    print("  Optimal beta: balances reward maximization with policy diversity.")


def exercise_4():
    """
    Exercise 4: DPO vs PPO — Trade-offs

    Compare DPO and PPO-based RLHF conceptually and numerically.
    """
    print("\nDPO vs PPO-Based RLHF:")
    print("=" * 60)

    print()
    print("  PPO-based RLHF:")
    print("    Step 1: Train reward model R_θ(x, y)")
    print("    Step 2: Use PPO to maximize E[R_θ] - beta*KL(pi||pi_ref)")
    print("    + Explicit reward model can be inspected and audited")
    print("    + Works with any RL algorithm, not just preference data")
    print("    - Two-stage: requires separate reward model training")
    print("    - RL sampling loop is computationally expensive")
    print("    - Reward model errors compound into policy errors")
    print()
    print("  DPO (Direct Preference Optimization):")
    print("    Single stage: directly optimize policy from preferences")
    print("    Loss: -log σ(β*(log π(y_w)/π_ref(y_w) - log π(y_l)/π_ref(y_l)))")
    print("    + Simpler: no RL loop, no reward model training")
    print("    + More stable optimization (just supervised fine-tuning)")
    print("    - No explicit reward model (harder to inspect)")
    print("    - Assumes preferences are well-calibrated IID data")
    print("    - Less flexible than PPO for non-preference objectives")
    print()

    # Numerical comparison of loss values
    np.random.seed(99)

    print("  DPO loss computation for example pairs:")
    print(f"  {'Case':>30} | {'log_pi_ratio_w':>16} | {'log_pi_ratio_l':>16} | {'DPO_loss':>10}")
    print("  " + "-" * 80)

    beta = 0.1
    cases = [
        ("Policy clearly correct", -1.0, -3.5, -2.0, -2.0),
        ("Policy neutral", -2.0, -2.0, -2.0, -2.0),
        ("Policy inverted", -4.0, -1.5, -2.0, -2.0),
        ("Large ratio diff", -0.5, -5.0, -2.0, -2.0),
    ]

    for name, lp_w, lp_l, lref_w, lref_l in cases:
        log_ratio_w = lp_w - lref_w
        log_ratio_l = lp_l - lref_l
        reward_diff = beta * (log_ratio_w - log_ratio_l)
        dpo_loss = -np.log(sigmoid(reward_diff) + 1e-10)
        print(f"  {name:>30} | {log_ratio_w:>16.3f} | {log_ratio_l:>16.3f} | {dpo_loss:>10.4f}")

    print()
    print("  Low DPO loss = policy correctly assigns higher probability to chosen.")
    print("  High DPO loss = policy needs to update toward preferred responses.")


if __name__ == "__main__":
    print("=== Exercise 1: RLHF Pipeline ===")
    exercise_1()

    print("\n=== Exercise 2: Bradley-Terry Model ===")
    exercise_2()

    print("\n=== Exercise 3: KL Penalty ===")
    exercise_3()

    print("\n=== Exercise 4: DPO vs PPO ===")
    exercise_4()

    print("\nAll exercises completed!")
