#!/bin/bash
# Exercises for Lesson 01: Git Basics
# Topic: Git
# Solutions to practice problems from the lesson.

# === Exercise 1: Install and Configure Git ===
# Problem: Verify Git is installed, configure user identity,
# and set a default editor.
exercise_1() {
    echo "=== Exercise 1: Install and Configure Git ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Verify Git is installed"
    echo "  git --version"
    echo "  # Output example: git version 2.43.0"
    echo ""
    echo "  # Step 2: Set your user name and email"
    echo "  # Why: Git embeds author info in every commit; this must be set first"
    echo "  git config --global user.name 'John Doe'"
    echo "  git config --global user.email 'john@example.com'"
    echo ""
    echo "  # Step 3: Set the default editor (optional but recommended)"
    echo "  git config --global core.editor 'vim'"
    echo "  # Or for VS Code: git config --global core.editor 'code --wait'"
    echo ""
    echo "  # Step 4: Verify configuration"
    echo "  git config --list"
    echo "  # Should display user.name, user.email, core.editor"
    echo ""
    echo "  # Step 5: Check individual values"
    echo "  git config user.name"
    echo "  # John Doe"
    echo "  git config user.email"
    echo "  # john@example.com"
    echo ""
    echo "Key takeaway:"
    echo "  Global config lives in ~/.gitconfig. Repository-level config"
    echo "  (git config without --global) overrides global for that repo."
}

# === Exercise 2: Initialize a Repository and Understand .git ===
# Problem: Create a new repository, inspect the .git directory,
# and understand what each entry does.
exercise_2() {
    echo "=== Exercise 2: Initialize a Repository and Understand .git ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Create a project directory and initialize Git"
    echo "  mkdir git-basics-lab"
    echo "  cd git-basics-lab"
    echo "  git init"
    echo "  # Output: Initialized empty Git repository in .../git-basics-lab/.git/"
    echo ""
    echo "  # Step 2: Explore the .git directory"
    echo "  ls -la .git/"
    echo "  # You should see: HEAD, config, objects/, refs/, hooks/, etc."
    echo ""
    echo "  # Step 3: Read the HEAD file"
    echo "  cat .git/HEAD"
    echo "  # Output: ref: refs/heads/main"
    echo "  # Why: HEAD tells Git which branch you are currently on"
    echo ""
    echo "  # Step 4: Check the config file"
    echo "  cat .git/config"
    echo "  # Shows repository-level settings (bare = false, etc.)"
    echo ""
    echo "  # Step 5: Confirm git status works in the new repo"
    echo "  git status"
    echo "  # On branch main"
    echo "  # No commits yet"
    echo "  # nothing to commit (create/copy files and use 'git add' to track)"
    echo ""
    echo "Key takeaway:"
    echo "  The .git/ directory IS the repository. The rest of the folder is"
    echo "  just the working directory. Delete .git/ and all history is gone."
}

# === Exercise 3: Three Areas Workflow ===
# Problem: Demonstrate the flow from working directory to staging area
# to repository by creating files and moving them through each stage.
exercise_3() {
    echo "=== Exercise 3: Three Areas Workflow ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Ensure you are inside a git-initialized directory"
    echo ""
    echo "  # Step 1: Create a file (working directory)"
    echo "  echo '# My Project' > README.md"
    echo "  git status"
    echo "  # README.md is listed as 'Untracked'"
    echo "  # The file exists only in the working directory"
    echo ""
    echo "  # Step 2: Stage the file (working directory -> staging area)"
    echo "  git add README.md"
    echo "  git status"
    echo "  # README.md is listed as 'Changes to be committed'"
    echo "  # The file is now in the staging area"
    echo ""
    echo "  # Step 3: Commit the file (staging area -> repository)"
    echo "  git commit -m 'feat: initialize project with README'"
    echo "  git status"
    echo "  # 'nothing to commit, working tree clean'"
    echo "  # The file is now stored as a snapshot in the repository"
    echo ""
    echo "  # Step 4: Verify the commit exists"
    echo "  git log --oneline"
    echo "  # <hash> feat: initialize project with README"
    echo ""
    echo "  # Step 5: Create a second file and repeat"
    echo "  echo 'print(\"hello\")' > app.py"
    echo "  git add app.py"
    echo "  git commit -m 'feat: add main application file'"
    echo "  git log --oneline"
    echo "  # <hash> feat: add main application file"
    echo "  # <hash> feat: initialize project with README"
    echo ""
    echo "Key takeaway:"
    echo "  Working directory -> git add -> Staging area -> git commit -> Repository."
    echo "  Each commit is an immutable snapshot. You can always return to it."
}

# === Exercise 4: Clone an Existing Repository ===
# Problem: Clone a remote repository and inspect its history
# to understand how clone differs from init.
exercise_4() {
    echo "=== Exercise 4: Clone an Existing Repository ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Clone a public repository"
    echo "  git clone https://github.com/octocat/Hello-World.git"
    echo "  cd Hello-World"
    echo ""
    echo "  # Step 2: Inspect the result"
    echo "  ls -la"
    echo "  # You see all project files plus the .git/ directory"
    echo ""
    echo "  # Step 3: View the commit history"
    echo "  git log --oneline -5"
    echo "  # Shows the most recent 5 commits from the remote"
    echo ""
    echo "  # Step 4: Check the remote configuration"
    echo "  git remote -v"
    echo "  # origin  https://github.com/octocat/Hello-World.git (fetch)"
    echo "  # origin  https://github.com/octocat/Hello-World.git (push)"
    echo "  # Why: clone automatically sets 'origin' as the remote name"
    echo ""
    echo "  # Step 5: List branches (local and remote)"
    echo "  git branch -a"
    echo "  # * main"
    echo "  #   remotes/origin/main"
    echo "  #   remotes/origin/HEAD -> origin/main"
    echo ""
    echo "Key takeaway:"
    echo "  git clone = git init + git remote add origin <url> + git fetch + git checkout."
    echo "  It creates a full copy of the repository including all history."
}

# === Exercise 5: Git vs GitHub Distinction ===
# Problem: Demonstrate that Git works entirely locally without
# any connection to GitHub or the internet.
exercise_5() {
    echo "=== Exercise 5: Git vs GitHub Distinction ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Disconnect from the internet (or just proceed locally)"
    echo "  # This exercise proves Git does not require GitHub"
    echo ""
    echo "  # Step 2: Create a local-only repository"
    echo "  mkdir offline-project"
    echo "  cd offline-project"
    echo "  git init"
    echo ""
    echo "  # Step 3: Make commits entirely offline"
    echo "  echo 'local work' > file1.txt"
    echo "  git add file1.txt"
    echo "  git commit -m 'feat: add file1'"
    echo ""
    echo "  echo 'more work' > file2.txt"
    echo "  git add file2.txt"
    echo "  git commit -m 'feat: add file2'"
    echo ""
    echo "  # Step 4: View history -- fully functional without internet"
    echo "  git log --oneline"
    echo "  # <hash> feat: add file2"
    echo "  # <hash> feat: add file1"
    echo ""
    echo "  # Step 5: Diff, branch, merge -- all local"
    echo "  git switch -c experiment"
    echo "  echo 'experiment' > exp.txt"
    echo "  git add exp.txt"
    echo "  git commit -m 'feat: add experiment'"
    echo "  git switch main"
    echo "  git merge experiment"
    echo ""
    echo "  # Step 6: Verify no remote is configured"
    echo "  git remote -v"
    echo "  # (no output -- no remote configured)"
    echo ""
    echo "Key takeaway:"
    echo "  Git is a local tool. GitHub is a remote hosting service."
    echo "  All core Git operations (commit, branch, merge, log, diff)"
    echo "  work entirely offline. GitHub adds collaboration features"
    echo "  (pull requests, issues, CI) on top of Git."
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
exercise_4
echo ""
exercise_5
echo ""
echo "All exercises completed!"
