#!/bin/bash
# Exercises for Lesson 02: Basic Commands
# Topic: Git
# Solutions to practice problems from the lesson.

# === Exercise 1: File Status Lifecycle ===
# Problem: Create files and observe them transition through all four
# states: untracked, staged, committed, and modified.
exercise_1() {
    echo "=== Exercise 1: File Status Lifecycle ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Create a new repository"
    echo "  mkdir status-lab && cd status-lab && git init"
    echo ""
    echo "  # Step 1: Untracked state"
    echo "  echo 'Hello Git' > hello.txt"
    echo "  echo 'Bye Git' > bye.txt"
    echo "  git status"
    echo "  # Both files are 'Untracked' -- Git sees them but is not tracking them"
    echo ""
    echo "  # Step 2: Staged state (stage only one file)"
    echo "  git add hello.txt"
    echo "  git status"
    echo "  # hello.txt: 'Changes to be committed' (staged)"
    echo "  # bye.txt: still 'Untracked'"
    echo ""
    echo "  # Step 3: Committed state"
    echo "  git commit -m 'feat: add hello.txt'"
    echo "  git status"
    echo "  # hello.txt is now committed (not shown in status)"
    echo "  # bye.txt: still 'Untracked'"
    echo ""
    echo "  # Step 4: Modified state"
    echo "  echo 'Nice to meet you!' >> hello.txt"
    echo "  git status"
    echo "  # hello.txt: 'Changes not staged for commit' (modified)"
    echo "  # bye.txt: still 'Untracked'"
    echo ""
    echo "  # Step 5: Stage and commit the modification"
    echo "  git add hello.txt"
    echo "  git commit -m 'docs: add greeting line to hello.txt'"
    echo "  git status"
    echo "  # 'nothing to commit' for tracked files; bye.txt still untracked"
    echo ""
    echo "Key takeaway:"
    echo "  Files cycle through: Untracked -> Staged -> Committed -> Modified -> Staged -> ..."
    echo "  git status is your primary tool for understanding where each file stands."
}

# === Exercise 2: Selective Staging with git add ===
# Problem: Stage specific files, use glob patterns, and demonstrate
# the difference between staging individual files vs all files.
exercise_2() {
    echo "=== Exercise 2: Selective Staging with git add ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Inside a git repository, create several files"
    echo "  echo 'app code' > app.js"
    echo "  echo 'test code' > test.js"
    echo "  echo 'style' > style.css"
    echo "  echo 'readme' > README.md"
    echo ""
    echo "  # Step 1: Stage only JavaScript files using a glob pattern"
    echo "  git add *.js"
    echo "  git status"
    echo "  # app.js and test.js: staged"
    echo "  # style.css and README.md: untracked"
    echo ""
    echo "  # Step 2: Unstage test.js (keep only app.js staged)"
    echo "  git restore --staged test.js"
    echo "  git status"
    echo "  # app.js: staged"
    echo "  # test.js, style.css, README.md: untracked"
    echo ""
    echo "  # Step 3: Commit only app.js"
    echo "  git commit -m 'feat: add main app file'"
    echo ""
    echo "  # Step 4: Stage remaining files individually"
    echo "  git add test.js style.css"
    echo "  git commit -m 'feat: add test and style files'"
    echo ""
    echo "  # Step 5: Stage everything with 'git add .'"
    echo "  git add ."
    echo "  git commit -m 'docs: add README'"
    echo ""
    echo "Key takeaway:"
    echo "  Selective staging lets you craft focused commits."
    echo "  Each commit should represent one logical change, not 'everything I did today.'"
}

# === Exercise 3: Writing Good Commit Messages ===
# Problem: Practice writing commits following the Conventional Commits
# convention and demonstrate git commit --amend for fixing messages.
exercise_3() {
    echo "=== Exercise 3: Writing Good Commit Messages ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Inside a git repository with at least one commit"
    echo ""
    echo "  # Step 1: Create a feature and commit with a proper message"
    echo "  echo 'function login() {}' > auth.js"
    echo "  git add auth.js"
    echo "  git commit -m 'feat: add login function stub'"
    echo ""
    echo "  # Step 2: Fix a bug and commit with proper type"
    echo "  echo 'function login() { return true; }' > auth.js"
    echo "  git add auth.js"
    echo "  git commit -m 'fix: return value from login function'"
    echo ""
    echo "  # Step 3: Update docs"
    echo "  echo '## Auth Module' >> README.md"
    echo "  git add README.md"
    echo "  git commit -m 'docs: document auth module in README'"
    echo ""
    echo "  # Step 4: Oops, we made a typo in the commit message"
    echo "  # Fix the LAST commit message with --amend"
    echo "  git commit --amend -m 'docs: add auth module documentation to README'"
    echo "  # Why: --amend replaces the last commit (same changes, new message)"
    echo ""
    echo "  # Step 5: Forgot to add a file to the last commit"
    echo "  echo 'auth API docs' > AUTH_API.md"
    echo "  git add AUTH_API.md"
    echo "  git commit --amend --no-edit"
    echo "  # Why: --no-edit keeps the existing message, just adds the new file"
    echo ""
    echo "  # Step 6: Verify the history"
    echo "  git log --oneline"
    echo "  # Three commits total (amend does not create new commits)"
    echo ""
    echo "Key takeaway:"
    echo "  Use conventional types (feat, fix, docs, refactor, test, chore)."
    echo "  Use --amend only for the most recent commit AND only before pushing."
}

# === Exercise 4: Exploring History with git log ===
# Problem: Use various git log options to explore commit history
# in different formats and filter by file or count.
exercise_4() {
    echo "=== Exercise 4: Exploring History with git log ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Use a repository with at least 5 commits"
    echo ""
    echo "  # Step 1: Basic log"
    echo "  git log"
    echo "  # Full details: hash, author, date, message"
    echo ""
    echo "  # Step 2: One-line compact format"
    echo "  git log --oneline"
    echo "  # Short hash + subject line only"
    echo ""
    echo "  # Step 3: Limit to last 3 commits"
    echo "  git log --oneline -3"
    echo ""
    echo "  # Step 4: Show graph with branch structure"
    echo "  git log --oneline --graph --all"
    echo "  # Why: --all includes all branches, --graph draws ASCII art"
    echo ""
    echo "  # Step 5: Show log for a specific file"
    echo "  git log --oneline -- README.md"
    echo "  # Only commits that touched README.md"
    echo ""
    echo "  # Step 6: Show log with diffs"
    echo "  git log -p -1"
    echo "  # -p shows the patch (diff) for each commit"
    echo "  # -1 limits to the most recent commit"
    echo ""
    echo "  # Step 7: Show stats (files changed, insertions, deletions)"
    echo "  git log --stat --oneline -3"
    echo ""
    echo "Key takeaway:"
    echo "  git log is highly customizable. --oneline for quick overview,"
    echo "  --graph for branch visualization, -p for detailed diffs,"
    echo "  and -- <file> to focus on a single file's history."
}

# === Exercise 5: Comparing Changes with git diff ===
# Problem: Use git diff to compare working directory vs staging area,
# staging area vs last commit, and between two commits.
exercise_5() {
    echo "=== Exercise 5: Comparing Changes with git diff ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Start with a committed file"
    echo "  echo 'line 1' > notes.txt"
    echo "  git add notes.txt && git commit -m 'feat: add notes file'"
    echo ""
    echo "  # Step 1: Modify the file (working directory change)"
    echo "  echo 'line 2' >> notes.txt"
    echo ""
    echo "  # Step 2: Diff working directory vs staging area"
    echo "  git diff"
    echo "  # Shows: +line 2 (the unstaged change)"
    echo ""
    echo "  # Step 3: Stage the change"
    echo "  git add notes.txt"
    echo ""
    echo "  # Step 4: Diff staging area vs last commit"
    echo "  git diff --staged"
    echo "  # Shows: +line 2 (the staged change awaiting commit)"
    echo "  # Why: plain 'git diff' shows nothing now because the change is staged"
    echo ""
    echo "  # Step 5: Make another modification WITHOUT staging"
    echo "  echo 'line 3' >> notes.txt"
    echo ""
    echo "  # Step 6: Now both diffs show different things"
    echo "  git diff"
    echo "  # Shows: +line 3 (unstaged change)"
    echo "  git diff --staged"
    echo "  # Shows: +line 2 (staged change)"
    echo ""
    echo "  # Step 7: Commit staged change, then compare two commits"
    echo "  git commit -m 'docs: add line 2 to notes'"
    echo "  git add notes.txt && git commit -m 'docs: add line 3 to notes'"
    echo ""
    echo "  # Compare the last two commits"
    echo "  git diff HEAD~1 HEAD"
    echo "  # Shows changes between the two commits"
    echo ""
    echo "Key takeaway:"
    echo "  git diff = working dir vs staging area."
    echo "  git diff --staged = staging area vs last commit."
    echo "  git diff <commit1> <commit2> = between any two commits."
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
exercise_4
echo ""
exercise_5
echo ""
echo "All exercises completed!"
