#!/bin/bash
# Exercises for Lesson 03: Branches
# Topic: Git
# Solutions to practice problems from the lesson.

# === Exercise 1: Create, Switch, and Delete Branches ===
# Problem: Practice the full branch lifecycle -- create, switch,
# work, and delete a branch.
exercise_1() {
    echo "=== Exercise 1: Create, Switch, and Delete Branches ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Create a repository with an initial commit"
    echo "  mkdir branch-lab && cd branch-lab && git init"
    echo "  echo '# Branch Lab' > README.md"
    echo "  git add README.md && git commit -m 'feat: initialize project'"
    echo ""
    echo "  # Step 1: List branches (only main exists)"
    echo "  git branch"
    echo "  # * main"
    echo ""
    echo "  # Step 2: Create a new branch (without switching)"
    echo "  git branch feature/greeting"
    echo "  git branch"
    echo "  #   feature/greeting"
    echo "  # * main"
    echo "  # Why: the * indicates you are still on main"
    echo ""
    echo "  # Step 3: Switch to the new branch"
    echo "  git switch feature/greeting"
    echo "  git branch"
    echo "  # * feature/greeting"
    echo "  #   main"
    echo ""
    echo "  # Step 4: Make a commit on the feature branch"
    echo "  echo 'function greet() { return \"Hello!\"; }' > greet.js"
    echo "  git add greet.js && git commit -m 'feat: add greeting function'"
    echo ""
    echo "  # Step 5: Switch back to main and verify greet.js does not exist"
    echo "  git switch main"
    echo "  ls greet.js 2>/dev/null || echo 'greet.js does not exist on main'"
    echo ""
    echo "  # Step 6: Delete the feature branch (after merging or with -D to force)"
    echo "  git merge feature/greeting"
    echo "  git branch -d feature/greeting"
    echo "  git branch"
    echo "  # * main  (feature/greeting is gone)"
    echo ""
    echo "  # Step 7: Shortcut -- create and switch in one command"
    echo "  git switch -c feature/farewell"
    echo "  echo 'function bye() { return \"Goodbye!\"; }' > bye.js"
    echo "  git add bye.js && git commit -m 'feat: add farewell function'"
    echo ""
    echo "Key takeaway:"
    echo "  Branches are cheap pointers to commits. Create them freely,"
    echo "  delete them after merging. Use 'git switch -c' for the"
    echo "  common create-and-switch pattern."
}

# === Exercise 2: Fast-Forward vs Three-Way Merge ===
# Problem: Create scenarios that result in a fast-forward merge
# and a three-way merge, and observe the difference.
exercise_2() {
    echo "=== Exercise 2: Fast-Forward vs Three-Way Merge ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # === Part A: Fast-Forward Merge ==="
    echo "  # Scenario: main has no new commits after branching"
    echo ""
    echo "  mkdir merge-lab && cd merge-lab && git init"
    echo "  echo 'v1' > app.txt"
    echo "  git add app.txt && git commit -m 'feat: initial version'"
    echo ""
    echo "  # Create feature branch and add commits"
    echo "  git switch -c feature/fast"
    echo "  echo 'v2' >> app.txt && git add . && git commit -m 'feat: add v2'"
    echo "  echo 'v3' >> app.txt && git add . && git commit -m 'feat: add v3'"
    echo ""
    echo "  # Merge into main (main has no new commits -> fast-forward)"
    echo "  git switch main"
    echo "  git merge feature/fast"
    echo "  # Output: Fast-forward"
    echo "  # Why: Git just moves the main pointer forward; no merge commit created"
    echo ""
    echo "  git log --oneline --graph"
    echo "  # Linear history -- no merge commit"
    echo ""
    echo "  # === Part B: Three-Way Merge ==="
    echo "  # Scenario: both main and the feature branch have new commits"
    echo ""
    echo "  git switch -c feature/three-way"
    echo "  echo 'feature work' > feature.txt"
    echo "  git add . && git commit -m 'feat: add feature file'"
    echo ""
    echo "  # Go back to main and create a diverging commit"
    echo "  git switch main"
    echo "  echo 'main work' > main.txt"
    echo "  git add . && git commit -m 'feat: add main file'"
    echo ""
    echo "  # Now merge (both branches diverged -> three-way merge)"
    echo "  git merge feature/three-way -m 'merge: integrate three-way feature'"
    echo "  # A merge commit is created"
    echo ""
    echo "  git log --oneline --graph"
    echo "  # Diamond shape visible: two lines converging into a merge commit"
    echo ""
    echo "Key takeaway:"
    echo "  Fast-forward: linear history, no merge commit. Happens when main"
    echo "  has not diverged. Three-way merge: creates a merge commit with two"
    echo "  parents. Happens when both branches have new commits."
}

# === Exercise 3: Resolve a Merge Conflict ===
# Problem: Intentionally create a merge conflict by modifying the
# same line in two branches, then resolve it manually.
exercise_3() {
    echo "=== Exercise 3: Resolve a Merge Conflict ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Repository with a shared file"
    echo "  mkdir conflict-lab && cd conflict-lab && git init"
    echo "  echo 'Hello World' > greeting.txt"
    echo "  git add . && git commit -m 'feat: add greeting'"
    echo ""
    echo "  # Step 1: Create a feature branch and modify the greeting"
    echo "  git switch -c feature/spanish"
    echo "  echo 'Hola Mundo' > greeting.txt"
    echo "  git add . && git commit -m 'feat: translate greeting to Spanish'"
    echo ""
    echo "  # Step 2: Switch to main and modify the SAME line differently"
    echo "  git switch main"
    echo "  echo 'Hello Everyone' > greeting.txt"
    echo "  git add . && git commit -m 'docs: update greeting text'"
    echo ""
    echo "  # Step 3: Attempt to merge -- conflict!"
    echo "  git merge feature/spanish"
    echo "  # CONFLICT (content): Merge conflict in greeting.txt"
    echo "  # Automatic merge failed; fix conflicts and then commit the result."
    echo ""
    echo "  # Step 4: Inspect the conflict markers"
    echo "  cat greeting.txt"
    echo "  # <<<<<<< HEAD"
    echo "  # Hello Everyone"
    echo "  # ======="
    echo "  # Hola Mundo"
    echo "  # >>>>>>> feature/spanish"
    echo ""
    echo "  # Step 5: Resolve by choosing both (or editing as needed)"
    echo "  # Edit greeting.txt to contain:"
    echo "  #   Hello Everyone"
    echo "  #   Hola Mundo"
    echo "  # Remove all conflict markers (<<<, ===, >>>)"
    echo ""
    echo "  # Step 6: Mark as resolved and complete the merge"
    echo "  git add greeting.txt"
    echo "  git commit -m 'merge: resolve greeting conflict, keep both languages'"
    echo ""
    echo "  # Step 7: Verify"
    echo "  cat greeting.txt"
    echo "  # Hello Everyone"
    echo "  # Hola Mundo"
    echo "  git log --oneline --graph"
    echo ""
    echo "  # Bonus: If the conflict is too messy, abort the merge entirely"
    echo "  # git merge --abort"
    echo "  # This returns you to the state before the merge attempt"
    echo ""
    echo "Key takeaway:"
    echo "  Conflicts happen when the same lines are changed in both branches."
    echo "  Resolution is manual: edit the file, remove markers, git add, git commit."
    echo "  Use git merge --abort if you need to start over."
}

# === Exercise 4: Branch Naming Conventions ===
# Problem: Practice using professional branch naming conventions
# (feature/, bugfix/, hotfix/, release/) in a realistic workflow.
exercise_4() {
    echo "=== Exercise 4: Branch Naming Conventions ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Repository simulating a team project"
    echo "  mkdir team-project && cd team-project && git init"
    echo "  echo '# Team Project v1.0' > README.md"
    echo "  git add . && git commit -m 'feat: initialize project'"
    echo ""
    echo "  # Step 1: Feature branch -- new functionality"
    echo "  git switch -c feature/user-authentication"
    echo "  echo 'auth module' > auth.py"
    echo "  git add . && git commit -m 'feat: add authentication module'"
    echo "  git switch main && git merge feature/user-authentication"
    echo "  git branch -d feature/user-authentication"
    echo ""
    echo "  # Step 2: Bugfix branch -- non-urgent bug"
    echo "  git switch -c bugfix/login-redirect"
    echo "  echo 'fixed redirect' > fix.py"
    echo "  git add . && git commit -m 'fix: correct login redirect URL'"
    echo "  git switch main && git merge bugfix/login-redirect"
    echo "  git branch -d bugfix/login-redirect"
    echo ""
    echo "  # Step 3: Hotfix branch -- urgent production fix"
    echo "  git switch -c hotfix/security-vulnerability"
    echo "  echo 'patched' > security.py"
    echo "  git add . && git commit -m 'fix: patch critical security vulnerability'"
    echo "  git switch main && git merge hotfix/security-vulnerability"
    echo "  git branch -d hotfix/security-vulnerability"
    echo ""
    echo "  # Step 4: Release branch -- preparing a release"
    echo "  git switch -c release/2.0.0"
    echo "  echo '# Team Project v2.0' > README.md"
    echo "  git add . && git commit -m 'chore: bump version to 2.0.0'"
    echo "  git switch main && git merge release/2.0.0"
    echo "  git branch -d release/2.0.0"
    echo ""
    echo "  # Step 5: View the clean history"
    echo "  git log --oneline"
    echo ""
    echo "Key takeaway:"
    echo "  Branch prefixes communicate intent at a glance:"
    echo "    feature/ = new functionality"
    echo "    bugfix/  = non-urgent bug fix"
    echo "    hotfix/  = urgent production fix"
    echo "    release/ = version release preparation"
}

# === Exercise 5: Branch Visualization and Cleanup ===
# Problem: Create multiple branches, visualize the branch graph,
# and clean up merged branches.
exercise_5() {
    echo "=== Exercise 5: Branch Visualization and Cleanup ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Repository with several branches"
    echo "  mkdir viz-lab && cd viz-lab && git init"
    echo "  echo 'base' > base.txt && git add . && git commit -m 'feat: base commit'"
    echo ""
    echo "  # Step 1: Create three feature branches with commits"
    echo "  git switch -c feature/a"
    echo "  echo 'a' > a.txt && git add . && git commit -m 'feat: add feature A'"
    echo ""
    echo "  git switch main"
    echo "  git switch -c feature/b"
    echo "  echo 'b' > b.txt && git add . && git commit -m 'feat: add feature B'"
    echo ""
    echo "  git switch main"
    echo "  git switch -c feature/c"
    echo "  echo 'c' > c.txt && git add . && git commit -m 'feat: add feature C'"
    echo ""
    echo "  # Step 2: Visualize all branches"
    echo "  git log --oneline --graph --all"
    echo "  # Shows three branches diverging from the base commit"
    echo ""
    echo "  # Step 3: Merge feature/a and feature/b into main"
    echo "  git switch main"
    echo "  git merge feature/a -m 'merge: feature A'"
    echo "  git merge feature/b -m 'merge: feature B'"
    echo ""
    echo "  # Step 4: Visualize again -- feature/c is still unmerged"
    echo "  git log --oneline --graph --all"
    echo ""
    echo "  # Step 5: List merged vs unmerged branches"
    echo "  git branch --merged"
    echo "  #   feature/a"
    echo "  #   feature/b"
    echo "  # * main"
    echo ""
    echo "  git branch --no-merged"
    echo "  #   feature/c"
    echo ""
    echo "  # Step 6: Clean up merged branches (safe -- only deletes fully merged)"
    echo "  git branch -d feature/a"
    echo "  git branch -d feature/b"
    echo "  # Both deleted successfully"
    echo ""
    echo "  # Step 7: Attempting to delete unmerged branch with -d fails safely"
    echo "  git branch -d feature/c"
    echo "  # error: The branch 'feature/c' is not fully merged."
    echo "  # Use -D to force delete if you are sure"
    echo ""
    echo "Key takeaway:"
    echo "  git branch --merged lists branches safe to delete."
    echo "  git branch -d is safe (refuses unmerged). git branch -D force-deletes."
    echo "  Regularly clean up merged branches to keep the repo tidy."
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
exercise_4
echo ""
exercise_5
echo ""
echo "All exercises completed!"
