#!/bin/bash
# Exercises for Lesson 05: GitHub Collaboration
# Topic: Git
# Solutions to practice problems from the lesson.

# === Exercise 1: Fork and Submit a Pull Request ===
# Problem: Fork the Spoon-Knife repo, clone, add upstream, create a branch,
# make changes, and open a Pull Request.
exercise_1() {
    echo "=== Exercise 1: Fork and Submit a Pull Request ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Fork the repository on GitHub"
    echo "  # Go to https://github.com/octocat/Spoon-Knife"
    echo "  # Click the 'Fork' button in the upper right corner"
    echo "  # This creates a copy at github.com/<your-username>/Spoon-Knife"
    echo ""
    echo "  # Step 2: Clone YOUR fork (not the original)"
    echo "  # Why: You push to your fork, then open a PR to the original"
    echo "  git clone git@github.com:<your-username>/Spoon-Knife.git"
    echo "  cd Spoon-Knife"
    echo ""
    echo "  # Step 3: Add the original repo as 'upstream'"
    echo "  # Why: upstream lets you sync with the original project"
    echo "  git remote add upstream git@github.com:octocat/Spoon-Knife.git"
    echo ""
    echo "  # Step 4: Verify both remotes"
    echo "  git remote -v"
    echo "  # origin    git@github.com:<your-username>/Spoon-Knife.git (fetch)"
    echo "  # origin    git@github.com:<your-username>/Spoon-Knife.git (push)"
    echo "  # upstream  git@github.com:octocat/Spoon-Knife.git (fetch)"
    echo "  # upstream  git@github.com:octocat/Spoon-Knife.git (push)"
    echo ""
    echo "  # Step 5: Create a feature branch"
    echo "  # Why: Never commit directly to main -- branches keep your fork clean"
    echo "  git switch -c add-my-name"
    echo ""
    echo "  # Step 6: Make a change and commit"
    echo "  echo '<your-github-username>' >> contributors.txt"
    echo "  git add contributors.txt"
    echo "  git commit -m 'docs: add my GitHub username to contributors'"
    echo ""
    echo "  # Step 7: Push to YOUR fork"
    echo "  git push -u origin add-my-name"
    echo ""
    echo "  # Step 8: Open a Pull Request on GitHub"
    echo "  # GitHub will show a 'Compare & pull request' banner"
    echo "  # Fill in the title and description following the PR template:"
    echo "  #   Title: 'Add <username> to contributors'"
    echo "  #   Description:"
    echo "  #     ## Changes"
    echo "  #     - Added my GitHub username to the contributors list"
    echo "  #     ## Related Issues"
    echo "  #     N/A"
    echo "  #     ## Testing"
    echo "  #     - [x] Verified the file renders correctly"
}

# === Exercise 2: Code Review Practice ===
# Problem: One person opens a PR, reviewer leaves inline comments,
# author addresses feedback, reviewer approves and merges.
exercise_2() {
    echo "=== Exercise 2: Code Review Practice ==="
    echo ""
    echo "Solution commands (two-person workflow):"
    echo ""
    echo "  # --- Person A (Author) ---"
    echo "  git switch -c feature/small-change"
    echo "  # Make a code change (e.g., add a function to a file)"
    echo "  git add ."
    echo "  git commit -m 'feat: add helper function'"
    echo "  git push -u origin feature/small-change"
    echo "  # Open PR on GitHub"
    echo ""
    echo "  # --- Person B (Reviewer) ---"
    echo "  # Go to the PR -> 'Files changed' tab"
    echo "  # Click the '+' icon next to specific lines to add inline comments"
    echo "  # Example comment 1: 'Consider adding input validation here'"
    echo "  # Example comment 2: 'This variable name could be more descriptive'"
    echo "  # Submit review as 'Request changes'"
    echo ""
    echo "  # --- Person A (Author addresses feedback) ---"
    echo "  # Why: New commits on the same branch automatically appear in the open PR"
    echo "  # Make the requested changes"
    echo "  git add ."
    echo "  git commit -m 'fix: apply review feedback - add validation and rename var'"
    echo "  git push origin feature/small-change"
    echo "  # The new commit appears in the PR timeline automatically"
    echo ""
    echo "  # --- Person B (Reviewer) ---"
    echo "  # Review the new commit in 'Files changed'"
    echo "  # If satisfied, submit review as 'Approve'"
    echo ""
    echo "  # --- Merge ---"
    echo "  # The author or reviewer (with write access) clicks 'Merge pull request'"
    echo "  # Choose merge strategy: 'Create a merge commit', 'Squash and merge', or 'Rebase and merge'"
    echo ""
    echo "Key takeaway:"
    echo "  PRs are living documents -- every push to the branch updates the PR."
    echo "  This creates a clear audit trail of review feedback and how it was addressed."
}

# === Exercise 3: Issues Workflow ===
# Problem: Create bug report and feature request issues, then link a PR
# that auto-closes the issue.
exercise_3() {
    echo "=== Exercise 3: Issues Workflow ==="
    echo ""
    echo "Solution steps:"
    echo ""
    echo "  # Step 1: Create a bug report issue"
    echo "  # Go to your repository -> Issues tab -> New Issue"
    echo "  # Use this format:"
    echo "  # Title: 'Bug: Login button unresponsive on mobile'"
    echo "  # Body:"
    echo "  #   ## Bug Description"
    echo "  #   The login button does not respond to taps on mobile devices."
    echo "  #"
    echo "  #   ## Reproduction Steps"
    echo "  #   1. Open the app on a mobile browser"
    echo "  #   2. Navigate to the login page"
    echo "  #   3. Tap the login button"
    echo "  #   4. Nothing happens"
    echo "  #"
    echo "  #   ## Expected Behavior"
    echo "  #   The login form should submit and redirect to the dashboard."
    echo "  #"
    echo "  #   ## Environment"
    echo "  #   - OS: iOS 17.2"
    echo "  #   - Browser: Safari 17"
    echo "  # Note the issue number (e.g., #1)"
    echo ""
    echo "  # Step 2: Create a feature request issue"
    echo "  # Title: 'Feature: Add dark mode toggle'"
    echo "  # Body:"
    echo "  #   ## Feature Description"
    echo "  #   Add a dark mode toggle to the settings page."
    echo "  #"
    echo "  #   ## Reason Needed"
    echo "  #   Reduces eye strain during nighttime use."
    echo "  #"
    echo "  #   ## Additional Information"
    echo "  #   See Material Design dark theme guidelines for reference."
    echo ""
    echo "  # Step 3: Create a PR that auto-closes the bug report"
    echo "  git switch -c bugfix/mobile-login"
    echo "  # Fix the bug..."
    echo "  git add ."
    echo "  git commit -m 'fix: make login button responsive on mobile'"
    echo "  git push -u origin bugfix/mobile-login"
    echo ""
    echo "  # In the PR description, include the magic keyword:"
    echo "  #   Closes #1"
    echo "  # Why: 'Closes', 'Fixes', or 'Resolves' followed by the issue number"
    echo "  #   will automatically close the referenced issue when the PR is merged."
    echo ""
    echo "  # After merging the PR, check that issue #1 is now closed automatically."
}

# === Exercise 4: Syncing a Fork ===
# Problem: Sync your fork with the original repo using fetch upstream + merge.
exercise_4() {
    echo "=== Exercise 4: Syncing a Fork ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Prerequisite: You have a fork with 'upstream' remote configured"
    echo "  # (from Exercise 1)"
    echo ""
    echo "  # Step 1: Simulate upstream changes"
    echo "  # Ask the repo owner to make a commit, or (if you own a test repo)"
    echo "  # make a commit via the GitHub web editor on the original repository"
    echo ""
    echo "  # Step 2: Fetch the latest from the original repository"
    echo "  # Why: This downloads new commits from upstream without modifying your code"
    echo "  git fetch upstream"
    echo ""
    echo "  # Step 3: Inspect the new commits before merging"
    echo "  # Why: Always review what you are about to integrate"
    echo "  git log upstream/main --oneline -5"
    echo "  git log main..upstream/main --oneline   # Only new commits"
    echo ""
    echo "  # Step 4: Merge upstream changes into your local main"
    echo "  git switch main"
    echo "  git merge upstream/main"
    echo "  # This should fast-forward if you have not made local commits on main"
    echo ""
    echo "  # Step 5: Push the updated main to YOUR fork"
    echo "  # Why: Your fork on GitHub is now behind -- this brings it up to date"
    echo "  git push origin main"
    echo ""
    echo "Key takeaway:"
    echo "  Regularly syncing your fork prevents large divergence and merge conflicts."
    echo "  Best practice: sync before starting any new feature branch."
}

# === Exercise 5: Branch Protection Rules ===
# Problem: Configure branch protection on main and observe the effects.
exercise_5() {
    echo "=== Exercise 5: Branch Protection Rules ==="
    echo ""
    echo "Solution steps:"
    echo ""
    echo "  # Step 1: Navigate to branch protection settings"
    echo "  # Go to: Repository -> Settings -> Branches -> Add branch protection rule"
    echo "  # Branch name pattern: 'main'"
    echo ""
    echo "  # Step 2: Enable protection rules"
    echo "  # Check: 'Require a pull request before merging'"
    echo "  #   Sub-option: 'Require approvals' (set to 1 or more)"
    echo "  # Check: 'Require status checks to pass before merging'"
    echo "  #   Select your CI workflow (e.g., 'build' or 'test')"
    echo "  # Click 'Create' or 'Save changes'"
    echo ""
    echo "  # Step 3: Attempt to push directly to main"
    echo "  git switch main"
    echo "  echo 'test' >> test.txt"
    echo "  git add test.txt"
    echo "  git commit -m 'test: try direct push'"
    echo "  git push origin main"
    echo "  # Expected: Push is REJECTED with an error message like:"
    echo "  # 'remote: error: GH006: Protected branch update failed'"
    echo ""
    echo "  # Step 4: The correct workflow with protection enabled"
    echo "  git switch -c fix/small-change"
    echo "  git push -u origin fix/small-change"
    echo "  # Open PR -> Get review -> Pass CI checks -> Merge via GitHub UI"
    echo ""
    echo "Why branch protection rules improve code quality:"
    echo ""
    echo "  1. PEER REVIEW: Every change is reviewed by at least one other person,"
    echo "     catching bugs, design issues, and knowledge gaps before they reach production."
    echo ""
    echo "  2. CI ENFORCEMENT: Automated tests must pass, preventing broken code from"
    echo "     being merged. This maintains a consistently deployable main branch."
    echo ""
    echo "  3. ACCOUNTABILITY: The PR history provides a clear audit trail of who"
    echo "     approved what and why, which is valuable for debugging and compliance."
    echo ""
    echo "  4. PREVENTS ACCIDENTS: Even admins cannot accidentally force-push or"
    echo "     commit directly, eliminating an entire class of human error."
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
exercise_4
echo ""
exercise_5
echo ""
echo "All exercises completed!"
