#!/bin/bash
# Exercises for Lesson 11: Git Internals
# Topic: Git
# Solutions to practice problems from the lesson.

# === Exercise 1: Explore the Object Database ===
# Problem: Create a repository, make a commit, and inspect the
# blob, tree, and commit objects using plumbing commands.
exercise_1() {
    echo "=== Exercise 1: Explore the Object Database ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Create a repository and commit a file"
    echo "  git init internals-lab && cd internals-lab"
    echo "  echo 'first file' > hello.txt"
    echo "  git add hello.txt"
    echo "  git commit -m 'Initial commit'"
    echo ""
    echo "  # Step 2: Find the blob hash of hello.txt"
    echo "  git ls-files --stage"
    echo "  # 100644 <blob-hash> 0  hello.txt"
    echo ""
    echo "  # Step 3: Inspect the blob object"
    echo "  git cat-file -t <blob-hash>"
    echo "  # blob"
    echo "  git cat-file -p <blob-hash>"
    echo "  # first file"
    echo "  git cat-file -s <blob-hash>"
    echo "  # 11  (byte count of 'first file\\n')"
    echo ""
    echo "  # Step 4: View the root tree of the latest commit"
    echo "  git ls-tree HEAD"
    echo "  # 100644 blob <blob-hash>  hello.txt"
    echo ""
    echo "  # Step 5: View the commit object itself"
    echo "  git cat-file -p HEAD"
    echo "  # tree <tree-hash>"
    echo "  # author John Doe <john@example.com> <timestamp>"
    echo "  # committer John Doe <john@example.com> <timestamp>"
    echo "  #"
    echo "  # Initial commit"
    echo ""
    echo "  # Step 6: Manually verify the blob hash"
    echo "  echo -en 'blob 11\0first file\n' | shasum"
    echo "  # Should match the blob hash from Step 2"
    echo ""
    echo "Key takeaway:"
    echo "  Every object in Git has a type (blob, tree, commit, tag),"
    echo "  and its hash is derived from its content. cat-file is the"
    echo "  Swiss Army knife for inspecting objects."
}

# === Exercise 2: Build a Commit with Plumbing Commands ===
# Problem: Create a complete commit using only low-level plumbing
# commands (no add, no commit).
exercise_2() {
    echo "=== Exercise 2: Build a Commit with Plumbing Commands ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Prerequisite: A git-initialized repo (from Exercise 1 or fresh)"
    echo ""
    echo "  # Step 1: Create a blob from content"
    echo "  BLOB_HASH=\$(echo 'plumbing test' | git hash-object -w --stdin)"
    echo "  echo \"Blob: \$BLOB_HASH\""
    echo "  # Why: -w writes the object to the database; --stdin reads from pipe"
    echo ""
    echo "  # Step 2: Add the blob to the index with a filename"
    echo "  git update-index --add --cacheinfo 100644 \$BLOB_HASH plumbing.txt"
    echo "  # Why: This is what 'git add' does internally"
    echo "  # 100644 = regular file mode"
    echo ""
    echo "  # Step 3: Write the index as a tree object"
    echo "  TREE_HASH=\$(git write-tree)"
    echo "  echo \"Tree: \$TREE_HASH\""
    echo "  # Why: The tree captures the directory state at this moment"
    echo ""
    echo "  # Step 4: Create a commit pointing to the tree"
    echo "  COMMIT_HASH=\$(echo 'Commit via plumbing commands' | git commit-tree \$TREE_HASH -p HEAD)"
    echo "  echo \"Commit: \$COMMIT_HASH\""
    echo "  # Why: -p HEAD sets the parent (chaining onto existing history)"
    echo ""
    echo "  # Step 5: Update the branch ref to point to the new commit"
    echo "  git update-ref refs/heads/main \$COMMIT_HASH"
    echo "  # Why: This is what moves the branch pointer forward"
    echo ""
    echo "  # Step 6: Verify with porcelain commands"
    echo "  git log --oneline -3"
    echo "  # Should show 'Commit via plumbing commands' as the latest"
    echo "  cat plumbing.txt 2>/dev/null || git show HEAD:plumbing.txt"
    echo "  # plumbing test"
    echo ""
    echo "Key takeaway:"
    echo "  'git add' + 'git commit' is syntactic sugar for hash-object +"
    echo "  update-index + write-tree + commit-tree + update-ref."
    echo "  Understanding this chain demystifies everything Git does."
}

# === Exercise 3: Content-Addressable Deduplication ===
# Problem: Demonstrate that identical content produces the same
# hash and is stored only once, regardless of filename.
exercise_3() {
    echo "=== Exercise 3: Content-Addressable Deduplication ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Create two files with identical content"
    echo "  echo 'shared content' > file_a.txt"
    echo "  echo 'shared content' > file_b.txt"
    echo "  git add file_a.txt file_b.txt"
    echo ""
    echo "  # Step 2: Check the staging area hashes"
    echo "  git ls-files --stage"
    echo "  # 100644 <same-hash> 0  file_a.txt"
    echo "  # 100644 <same-hash> 0  file_b.txt"
    echo "  # Both files share the SAME blob hash!"
    echo ""
    echo "  # Step 3: Verify only one blob object exists for the content"
    echo "  HASH=\$(git hash-object file_a.txt)"
    echo "  ls .git/objects/\${HASH:0:2}/\${HASH:2}"
    echo "  # Only one object file -- Git stored the content once"
    echo ""
    echo "  # Step 4: Create a file with DIFFERENT content"
    echo "  echo 'unique content' > file_c.txt"
    echo "  git add file_c.txt"
    echo "  git ls-files --stage"
    echo "  # file_c.txt has a different hash from file_a.txt and file_b.txt"
    echo ""
    echo "  # Step 5: Verify the tree maps filenames to blobs"
    echo "  git commit -m 'test: deduplication demo'"
    echo "  git ls-tree HEAD"
    echo "  # file_a.txt and file_b.txt point to the same blob"
    echo "  # file_c.txt points to a different blob"
    echo ""
    echo "Key takeaway:"
    echo "  Git is a content-addressable filesystem. Filenames are stored"
    echo "  in tree objects, not in blobs. Identical content = identical hash ="
    echo "  stored once. This makes Git surprisingly space-efficient."
}

# === Exercise 4: DAG Traversal and Ancestry References ===
# Problem: Create a branch-and-merge history and navigate it
# using ancestry references (HEAD~, HEAD^, rev-list).
exercise_4() {
    echo "=== Exercise 4: DAG Traversal and Ancestry References ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Create a repo with branching history"
    echo "  git init dag-lab && cd dag-lab"
    echo "  echo 'A' > a.txt && git add . && git commit -m 'Commit A'"
    echo "  echo 'B' > b.txt && git add . && git commit -m 'Commit B'"
    echo ""
    echo "  git switch -c feature"
    echo "  echo 'C' > c.txt && git add . && git commit -m 'Commit C (feature)'"
    echo "  echo 'D' > d.txt && git add . && git commit -m 'Commit D (feature)'"
    echo ""
    echo "  git switch main"
    echo "  echo 'E' > e.txt && git add . && git commit -m 'Commit E (main)'"
    echo "  git merge feature -m 'Merge feature into main'"
    echo ""
    echo "  # Step 2: Use ancestry references on the merge commit"
    echo "  git log --oneline -1 HEAD"
    echo "  # Merge commit (M)"
    echo ""
    echo "  git log --oneline -1 HEAD^1"
    echo "  # First parent: Commit E (the main-line parent)"
    echo ""
    echo "  git log --oneline -1 HEAD^2"
    echo "  # Second parent: Commit D (the feature-branch parent)"
    echo ""
    echo "  git log --oneline -1 HEAD~1"
    echo "  # Same as HEAD^1: Commit E"
    echo ""
    echo "  git log --oneline -1 HEAD~2"
    echo "  # Grandparent via first-parent: Commit B"
    echo ""
    echo "  # Step 3: Use rev-list to traverse the DAG"
    echo "  git rev-list --count HEAD"
    echo "  # Total reachable commits (6: A, B, C, D, E, Merge)"
    echo ""
    echo "  git rev-list HEAD --not feature"
    echo "  # Commits on main after the branch point"
    echo ""
    echo "  # Step 4: Find the common ancestor"
    echo "  git merge-base main feature"
    echo "  # Returns the hash of Commit B (where they diverged)"
    echo ""
    echo "Key takeaway:"
    echo "  HEAD~N follows first-parent links (linear ancestry)."
    echo "  HEAD^N selects the Nth parent of a merge commit."
    echo "  rev-list and merge-base let you query the DAG programmatically."
}

# === Exercise 5: Pack Files and Garbage Collection ===
# Problem: Observe loose objects, trigger packing, and compare
# storage efficiency before and after gc.
exercise_5() {
    echo "=== Exercise 5: Pack Files and Garbage Collection ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Create a repo with several commits"
    echo "  git init pack-lab && cd pack-lab"
    echo "  for i in 1 2 3 4 5; do"
    echo "    echo \"version \$i\" > data.txt"
    echo "    git add data.txt"
    echo "    git commit -m \"Update data to version \$i\""
    echo "  done"
    echo ""
    echo "  # Step 2: Count loose objects"
    echo "  git count-objects -v"
    echo "  # count: N       (loose objects)"
    echo "  # in-pack: 0     (no pack files yet)"
    echo ""
    echo "  # Step 3: Run garbage collection to pack objects"
    echo "  git gc"
    echo "  # Enumerating objects: done."
    echo "  # Counting objects: done."
    echo "  # Compressing objects: done."
    echo ""
    echo "  # Step 4: Check objects again"
    echo "  git count-objects -v"
    echo "  # count: 0       (no more loose objects)"
    echo "  # in-pack: N     (all objects are now packed)"
    echo "  # size-pack: M   (total pack size in KB)"
    echo ""
    echo "  # Step 5: Inspect the pack file"
    echo "  git verify-pack -v .git/objects/pack/pack-*.idx | head -15"
    echo "  # Shows each object with type, size, and delta information"
    echo "  # Objects with a 'depth' column are delta-compressed against a base"
    echo ""
    echo "  # Step 6: Verify repository integrity"
    echo "  git fsck"
    echo "  # Should report no errors"
    echo ""
    echo "Key takeaway:"
    echo "  Loose objects are individual compressed files (one per object)."
    echo "  git gc packs them using delta compression, dramatically reducing"
    echo "  disk usage. Git runs gc automatically when thresholds are reached."
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
exercise_4
echo ""
exercise_5
echo ""
echo "All exercises completed!"
