#!/bin/bash
# Exercises for Lesson 12: Git Bisect and Debugging
# Topic: Git
# Solutions to practice problems from the lesson.

# === Exercise 1: Manual Bisect ===
# Problem: Create a repository with 10 commits where a bug is
# introduced at commit 6, then use git bisect to find it.
exercise_1() {
    echo "=== Exercise 1: Manual Bisect ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Create a repository with 10 commits (bug at commit 6)"
    echo "  git init bisect-lab && cd bisect-lab"
    echo "  for i in \$(seq 1 10); do"
    echo "    echo \"version \$i\" > app.py"
    echo "    if [ \$i -eq 6 ]; then"
    echo "      echo 'BUG INTRODUCED' >> app.py"
    echo "    fi"
    echo "    git add app.py"
    echo "    git commit -m \"Commit \$i\""
    echo "  done"
    echo ""
    echo "  # Step 2: Note the first commit hash"
    echo "  FIRST_COMMIT=\$(git rev-list --max-parents=0 HEAD)"
    echo ""
    echo "  # Step 3: Start bisecting"
    echo "  git bisect start"
    echo "  git bisect bad HEAD         # Current state has the bug"
    echo "  git bisect good \$FIRST_COMMIT  # First commit was clean"
    echo "  # Bisecting: 4 revisions left to test after this (roughly 3 steps)"
    echo ""
    echo "  # Step 4: At each checkout, test for the bug"
    echo "  grep -q 'BUG INTRODUCED' app.py && git bisect bad || git bisect good"
    echo "  # Repeat this command at each step"
    echo "  # Git narrows the range by half each time"
    echo ""
    echo "  # Step 5: After ~3-4 steps, Git reports:"
    echo "  # <hash> is the first bad commit"
    echo "  # commit <hash>"
    echo "  # Author: ..."
    echo "  #     Commit 6"
    echo ""
    echo "  # Step 6: Return to your original branch"
    echo "  git bisect reset"
    echo ""
    echo "Key takeaway:"
    echo "  Bisect uses binary search: 10 commits need ~3-4 steps instead of 10."
    echo "  For 1000 commits, you need only ~10 steps. Always reset when done."
}

# === Exercise 2: Automated Bisect ===
# Problem: Use git bisect run with a test script to automatically
# find the commit that introduced a bug.
exercise_2() {
    echo "=== Exercise 2: Automated Bisect ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Using the same repository from Exercise 1"
    echo "  # (or recreate it with the same setup script)"
    echo ""
    echo "  # Step 1: Identify the first commit"
    echo "  FIRST_COMMIT=\$(git rev-list --max-parents=0 HEAD)"
    echo ""
    echo "  # Step 2: Start automated bisect"
    echo "  git bisect start HEAD \$FIRST_COMMIT"
    echo ""
    echo "  # Step 3: Run with an inline test command"
    echo "  # Why: Exit code 0 = good (no bug), exit code 1 = bad (bug found)"
    echo "  git bisect run sh -c 'grep -q \"BUG INTRODUCED\" app.py && exit 1 || exit 0'"
    echo ""
    echo "  # Git automatically tests each midpoint and reports:"
    echo "  # <hash> is the first bad commit"
    echo "  # Bisect run successful"
    echo ""
    echo "  # Step 4: For more complex scenarios, use a test script"
    echo "  # Create bisect_test.sh:"
    echo "  # #!/bin/bash"
    echo "  # make clean && make 2>/dev/null"
    echo "  # if [ \$? -ne 0 ]; then"
    echo "  #     exit 125  # 125 = skip (cannot test this commit)"
    echo "  # fi"
    echo "  # python -m pytest tests/test_auth.py -x --tb=no"
    echo "  # exit \$?"
    echo ""
    echo "  # chmod +x bisect_test.sh"
    echo "  # git bisect start HEAD v1.0"
    echo "  # git bisect run ./bisect_test.sh"
    echo ""
    echo "  # Step 5: Clean up"
    echo "  git bisect reset"
    echo ""
    echo "Key takeaway:"
    echo "  Automated bisect is hands-free bug hunting. The test script's exit"
    echo "  codes: 0=good, 1-124/126-127=bad, 125=skip. Use exit 125 when a"
    echo "  commit cannot be tested (e.g., build failure unrelated to the bug)."
}

# === Exercise 3: Code Archaeology with git blame ===
# Problem: Use git blame to find who changed specific lines,
# and use -L, -w, and -C options for deeper analysis.
exercise_3() {
    echo "=== Exercise 3: Code Archaeology with git blame ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Create a file with multiple authors (simulated)"
    echo "  git init blame-lab && cd blame-lab"
    echo "  cat > auth.py << 'PYEOF'"
    echo "import hashlib"
    echo "import os"
    echo ""
    echo "def hash_password(password):"
    echo "    salt = os.urandom(16)"
    echo "    return hashlib.sha256(salt + password.encode()).hexdigest()"
    echo "PYEOF"
    echo "  git add auth.py && git commit -m 'feat: add password hashing'"
    echo ""
    echo "  # Add a second function in a new commit"
    echo "  cat >> auth.py << 'PYEOF'"
    echo ""
    echo "def verify_password(password, stored_hash):"
    echo "    return hash_password(password) == stored_hash"
    echo "PYEOF"
    echo "  git add auth.py && git commit -m 'feat: add password verification'"
    echo ""
    echo "  # Step 1: Basic blame -- who changed each line?"
    echo "  git blame auth.py"
    echo "  # Each line shows: commit-hash, author, date, line-number, content"
    echo ""
    echo "  # Step 2: Blame a specific line range"
    echo "  git blame -L 4,6 auth.py"
    echo "  # Only shows lines 4-6 (the hash_password function)"
    echo ""
    echo "  # Step 3: Ignore whitespace changes"
    echo "  git blame -w auth.py"
    echo "  # Skips commits that only changed indentation/whitespace"
    echo ""
    echo "  # Step 4: Detect code moved from another file"
    echo "  git blame -C auth.py"
    echo "  # -C detects lines copied from other files in the same commit"
    echo "  # -C -C detects across commits"
    echo ""
    echo "  # Step 5: Blame at a specific past revision"
    echo "  git blame HEAD~1 -- auth.py"
    echo "  # Shows blame as of the previous commit (before verify_password)"
    echo ""
    echo "Key takeaway:"
    echo "  git blame answers 'who changed this line and when?' Use -L for"
    echo "  specific ranges, -w to skip whitespace-only commits, -C to track"
    echo "  code movement across files."
}

# === Exercise 4: Pickaxe Search with git log -S and -G ===
# Problem: Use -S and -G to find when specific strings or patterns
# were added, removed, or modified in the codebase.
exercise_4() {
    echo "=== Exercise 4: Pickaxe Search with git log -S and -G ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Setup: Create a repo with several commits changing a function"
    echo "  git init pickaxe-lab && cd pickaxe-lab"
    echo ""
    echo "  echo 'def validate_email(email): pass' > utils.py"
    echo "  git add . && git commit -m 'feat: add email validation stub'"
    echo ""
    echo "  echo 'def validate_email(email): return \"@\" in email' > utils.py"
    echo "  git add . && git commit -m 'feat: implement email validation'"
    echo ""
    echo "  echo 'def verify_email(email): return \"@\" in email' > utils.py"
    echo "  git add . && git commit -m 'refactor: rename validate to verify'"
    echo ""
    echo "  # Step 1: Find when 'validate_email' was added or removed"
    echo "  git log -S 'validate_email' --oneline"
    echo "  # Shows commits where the count of 'validate_email' changed"
    echo "  # Should show the commit that added it and the one that renamed it"
    echo ""
    echo "  # Step 2: Find when 'validate_email' appeared in any diff line"
    echo "  git log -G 'validate_email' --oneline"
    echo "  # Shows commits where any changed line contains 'validate_email'"
    echo ""
    echo "  # Step 3: See the actual diff"
    echo "  git log -S 'validate_email' -p"
    echo "  # Shows full patch for each matching commit"
    echo ""
    echo "  # Step 4: Limit search to specific file types"
    echo "  git log -S 'validate_email' -- '*.py'"
    echo "  # Only searches in Python files"
    echo ""
    echo "  # Step 5: Use -G with regex for pattern matching"
    echo "  git log -G 'def (validate|verify)_' --oneline"
    echo "  # Finds commits where any changed line matches the regex"
    echo ""
    echo "Key takeaway:"
    echo "  -S (pickaxe) finds commits that change the COUNT of a string."
    echo "  -G finds commits where any diff line MATCHES a regex."
    echo "  Use -S to find when something was added/removed, -G for modifications."
}

# === Exercise 5: Reflog Recovery ===
# Problem: Simulate losing commits via hard reset and a deleted
# branch, then recover everything using git reflog.
exercise_5() {
    echo "=== Exercise 5: Reflog Recovery ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Create a repository with meaningful commits"
    echo "  git init recovery-lab && cd recovery-lab"
    echo "  echo 'v1' > app.py && git add . && git commit -m 'feat: version 1'"
    echo "  echo 'v2' > app.py && git add . && git commit -m 'feat: version 2'"
    echo "  echo 'v3' > app.py && git add . && git commit -m 'feat: version 3'"
    echo ""
    echo "  # Step 2: Simulate accidental hard reset"
    echo "  git reset --hard HEAD~2"
    echo "  git log --oneline"
    echo "  # Only 'version 1' remains -- v2 and v3 appear lost!"
    echo ""
    echo "  # Step 3: Use reflog to find the lost commits"
    echo "  git reflog"
    echo "  # <hash> HEAD@{0}: reset: moving to HEAD~2"
    echo "  # <hash> HEAD@{1}: commit: feat: version 3  <- Target!"
    echo "  # <hash> HEAD@{2}: commit: feat: version 2"
    echo "  # <hash> HEAD@{3}: commit: feat: version 1"
    echo ""
    echo "  # Step 4: Recover by resetting to the pre-reset state"
    echo "  git reset --hard HEAD@{1}"
    echo "  git log --oneline"
    echo "  # All three commits are back!"
    echo ""
    echo "  # === Bonus: Recover a deleted branch ==="
    echo ""
    echo "  # Step 5: Create and delete a branch"
    echo "  git switch -c feature/important"
    echo "  echo 'critical work' > important.txt"
    echo "  git add . && git commit -m 'feat: critical feature'"
    echo "  git switch main"
    echo "  git branch -D feature/important"
    echo "  # Branch is gone!"
    echo ""
    echo "  # Step 6: Find the branch tip in reflog"
    echo "  git reflog | head -10"
    echo "  # Look for 'checkout: moving from feature/important to main'"
    echo "  # The SHA just before that entry is the branch tip"
    echo ""
    echo "  # Step 7: Recreate the branch"
    echo "  git branch feature/important <sha-from-reflog>"
    echo "  git log --oneline feature/important"
    echo "  # The 'critical feature' commit is recovered!"
    echo ""
    echo "Key takeaway:"
    echo "  The reflog records every HEAD movement. Even after reset --hard"
    echo "  or branch deletion, commits persist for ~90 days. Always check"
    echo "  git reflog before panicking about lost work."
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
exercise_4
echo ""
exercise_5
echo ""
echo "All exercises completed!"
