#!/bin/bash
# Exercises for Lesson 13: Monorepo Workflows
# Topic: Git
# Solutions to practice problems from the lesson.

# === Exercise 1: Affected-Based CI Detection ===
# Problem: Set up a monorepo structure and use Git to detect
# which packages changed, then design a CI pipeline that only
# builds/tests affected packages.
exercise_1() {
    echo "=== Exercise 1: Affected-Based CI Detection ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Create a monorepo structure"
    echo "  mkdir monorepo-lab && cd monorepo-lab && git init"
    echo "  mkdir -p packages/{api,web,shared,mobile}"
    echo "  echo 'api code' > packages/api/index.js"
    echo "  echo 'web code' > packages/web/index.js"
    echo "  echo 'shared utils' > packages/shared/index.js"
    echo "  echo 'mobile code' > packages/mobile/index.js"
    echo "  git add . && git commit -m 'feat: initialize monorepo structure'"
    echo ""
    echo "  # Step 2: Make a change in packages/api only"
    echo "  echo 'api v2' >> packages/api/index.js"
    echo "  git add . && git commit -m 'feat: update api'"
    echo ""
    echo "  # Step 3: Detect which packages changed since the previous commit"
    echo "  git diff --name-only HEAD~1 HEAD"
    echo "  # packages/api/index.js"
    echo ""
    echo "  # Step 4: Extract unique package names from changed paths"
    echo "  git diff --name-only HEAD~1 HEAD | cut -d'/' -f1-2 | sort -u"
    echo "  # packages/api"
    echo ""
    echo "  # Step 5: Design a CI script that uses this detection"
    echo "  echo '#!/bin/bash' > detect_affected.sh"
    echo "  echo 'CHANGED=\$(git diff --name-only \$1...\$2 | cut -d\"/\" -f1-2 | sort -u)' >> detect_affected.sh"
    echo "  echo 'for pkg in \$CHANGED; do' >> detect_affected.sh"
    echo "  echo '  echo \"Building and testing: \$pkg\"' >> detect_affected.sh"
    echo "  echo '  # npm run build -w \$pkg' >> detect_affected.sh"
    echo "  echo '  # npm run test -w \$pkg' >> detect_affected.sh"
    echo "  echo 'done' >> detect_affected.sh"
    echo ""
    echo "  # Step 6: Account for shared dependencies"
    echo "  # If packages/shared changes, rebuild ALL packages that depend on it"
    echo "  echo 'if echo \"\$CHANGED\" | grep -q \"packages/shared\"; then' >> detect_affected.sh"
    echo "  echo '  echo \"Shared changed -- rebuilding all dependents\"' >> detect_affected.sh"
    echo "  echo '  # npm run build --workspaces' >> detect_affected.sh"
    echo "  echo 'fi' >> detect_affected.sh"
    echo ""
    echo "Key takeaway:"
    echo "  Affected-based CI avoids rebuilding the entire monorepo on every push."
    echo "  Use git diff --name-only to detect changes, then map paths to packages."
    echo "  Always account for shared dependencies that affect multiple packages."
}

# === Exercise 2: CODEOWNERS Design ===
# Problem: Design a CODEOWNERS file for a monorepo with multiple
# teams and ownership patterns.
exercise_2() {
    echo "=== Exercise 2: CODEOWNERS Design ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Create the monorepo directory structure"
    echo "  mkdir -p .github"
    echo "  mkdir -p packages/{api,web,mobile,shared,auth}"
    echo "  mkdir -p packages/{api,web,mobile}/tests"
    echo "  mkdir -p packages/{api,web,mobile}/docs"
    echo "  mkdir -p scripts"
    echo "  mkdir -p docs"
    echo ""
    echo "  # Step 2: Write the CODEOWNERS file"
    echo "  cat > .github/CODEOWNERS << 'EOF'"
    echo "# Default: platform team owns everything not covered below"
    echo "*                               @org/platform-team"
    echo ""
    echo "# Package-level ownership"
    echo "/packages/api/                  @org/backend-team"
    echo "/packages/web/                  @org/frontend-team"
    echo "/packages/mobile/               @org/mobile-team"
    echo "/packages/shared/               @org/platform-team"
    echo ""
    echo "# Security-sensitive: requires BOTH teams"
    echo "/packages/auth/                 @org/security-team @org/backend-team"
    echo ""
    echo "# File-type ownership"
    echo "*.sql                           @org/database-team"
    echo "Dockerfile                      @org/devops-team"
    echo ""
    echo "# CI/CD and infrastructure"
    echo "/.github/                       @org/devops-team"
    echo "/scripts/                       @org/devops-team"
    echo ""
    echo "# QA owns all test directories"
    echo "/packages/*/tests/              @org/qa-team"
    echo ""
    echo "# Documentation"
    echo "/docs/                          @org/docs-team"
    echo "EOF"
    echo ""
    echo "  # Step 3: Commit and verify"
    echo "  git add .github/CODEOWNERS"
    echo "  git commit -m 'chore: add CODEOWNERS for team-based reviews'"
    echo ""
    echo "  # Step 4: Enable branch protection (GitHub UI or API)"
    echo "  # Settings -> Branches -> Branch protection rules:"
    echo "  # - Require pull request reviews"
    echo "  # - Require review from Code Owners"
    echo "  # - Dismiss stale reviews on new commits"
    echo ""
    echo "Key takeaway:"
    echo "  CODEOWNERS automates review assignment. More specific patterns"
    echo "  override less specific ones. Combine with branch protection"
    echo "  to enforce mandatory code review from the correct team."
}

# === Exercise 3: Sparse Checkout for Large Repos ===
# Problem: Clone a monorepo using partial clone and sparse checkout
# to work with only specific packages.
exercise_3() {
    echo "=== Exercise 3: Sparse Checkout for Large Repos ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Clone with blobless partial clone (skips file content)"
    echo "  git clone --filter=blob:none --sparse https://github.com/org/monorepo.git"
    echo "  cd monorepo"
    echo "  # Why: --filter=blob:none downloads metadata only; blobs fetched on demand"
    echo "  # Why: --sparse initializes sparse checkout (empty working tree)"
    echo ""
    echo "  # Step 2: Configure sparse checkout for your packages"
    echo "  git sparse-checkout set packages/web packages/shared"
    echo "  # Only packages/web/ and packages/shared/ are checked out"
    echo "  # All other directories appear empty"
    echo ""
    echo "  # Step 3: Verify sparse checkout"
    echo "  git sparse-checkout list"
    echo "  # packages/web"
    echo "  # packages/shared"
    echo ""
    echo "  ls packages/"
    echo "  # web/  shared/"
    echo "  # Other package directories are not present"
    echo ""
    echo "  # Step 4: Add another package to your checkout"
    echo "  git sparse-checkout add packages/api"
    echo "  git sparse-checkout list"
    echo "  # packages/api"
    echo "  # packages/web"
    echo "  # packages/shared"
    echo ""
    echo "  # Step 5: Enable performance optimizations"
    echo "  git config core.fsmonitor true"
    echo "  git config core.untrackedCache true"
    echo "  git config fetch.writeCommitGraph true"
    echo ""
    echo "  # Step 6: Compare disk usage"
    echo "  du -sh .git"
    echo "  # Much smaller than a full clone"
    echo ""
    echo "  # Step 7: Disable sparse checkout (get everything back)"
    echo "  # git sparse-checkout disable"
    echo ""
    echo "Key takeaway:"
    echo "  Partial clone + sparse checkout lets you work in a massive monorepo"
    echo "  while only downloading the files you need. Ideal for repos with"
    echo "  hundreds of packages where each developer only touches a few."
}

# === Exercise 4: Changeset-Based Versioning ===
# Problem: Set up changesets in a monorepo and walk through the
# versioning and release workflow.
exercise_4() {
    echo "=== Exercise 4: Changeset-Based Versioning ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Initialize a monorepo with npm workspaces"
    echo "  mkdir changeset-lab && cd changeset-lab"
    echo "  npm init -y"
    echo "  # Add \"workspaces\": [\"packages/*\"] to package.json"
    echo ""
    echo "  mkdir -p packages/{core,utils,cli}"
    echo "  cd packages/core && npm init -y --scope=@myorg && cd ../.."
    echo "  cd packages/utils && npm init -y --scope=@myorg && cd ../.."
    echo "  cd packages/cli && npm init -y --scope=@myorg && cd ../.."
    echo ""
    echo "  git init && git add . && git commit -m 'feat: initialize monorepo'"
    echo ""
    echo "  # Step 2: Install and initialize changesets"
    echo "  npm install @changesets/cli -D"
    echo "  npx changeset init"
    echo "  # Creates .changeset/ directory with config.json and README.md"
    echo ""
    echo "  # Step 3: Create a changeset for a feature change"
    echo "  npx changeset"
    echo "  # Interactive prompts:"
    echo "  #   Which packages? @myorg/core"
    echo "  #   Major/minor/patch? minor"
    echo "  #   Summary: Add pagination support"
    echo "  # Creates .changeset/<random-name>.md"
    echo ""
    echo "  # Step 4: Version packages (consumes changesets)"
    echo "  npx changeset version"
    echo "  # Updates package.json versions"
    echo "  # Updates CHANGELOG.md files"
    echo "  # Removes consumed changeset files"
    echo ""
    echo "  # Step 5: Publish (in CI, after merging the version PR)"
    echo "  # npx changeset publish"
    echo ""
    echo "Key takeaway:"
    echo "  Changesets decouple 'what changed' from 'when to release.'"
    echo "  Developers create changeset files during PRs. The release"
    echo "  process consumes them to bump versions and generate changelogs."
}

# === Exercise 5: Git Performance Configuration ===
# Problem: Apply performance optimizations for a large repository
# and measure the impact on common operations.
exercise_5() {
    echo "=== Exercise 5: Git Performance Configuration ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Measure baseline git status time"
    echo "  time git status"
    echo "  # Note the real time"
    echo ""
    echo "  # Step 2: Enable filesystem monitor (Git 2.37+)"
    echo "  git config core.fsmonitor true"
    echo "  git config core.untrackedCache true"
    echo "  # Why: fsmonitor uses OS-level file watching instead of scanning"
    echo "  # every file. untrackedCache remembers which directories have no"
    echo "  # untracked files."
    echo ""
    echo "  # Step 3: Enable commit graph for faster log/merge-base"
    echo "  git commit-graph write --reachable"
    echo "  git config fetch.writeCommitGraph true"
    echo "  # Why: Precomputed graph accelerates DAG traversal"
    echo ""
    echo "  # Step 4: Enable parallel operations"
    echo "  git config index.threads true"
    echo "  git config pack.threads 0       # 0 = use all CPU cores"
    echo "  git config core.preloadIndex true"
    echo ""
    echo "  # Step 5: Enable large repo feature flag"
    echo "  git config feature.manyFiles true"
    echo "  # Why: Umbrella setting that enables multiple optimizations"
    echo ""
    echo "  # Step 6: Measure optimized git status time"
    echo "  git status  # First run primes the fsmonitor cache"
    echo "  time git status  # Second run should be faster"
    echo ""
    echo "  # Step 7: Verify all settings"
    echo "  git config --list --local | grep -E '(fsmonitor|untracked|commit-graph|threads|preload|manyFiles)'"
    echo ""
    echo "Key takeaway:"
    echo "  For repositories with thousands of files, these optimizations"
    echo "  can reduce git status from seconds to milliseconds."
    echo "  fsmonitor and untrackedCache provide the biggest wins."
    echo "  commit-graph accelerates log traversal and merge-base lookups."
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
exercise_4
echo ""
exercise_5
echo ""
echo "All exercises completed!"
