#!/bin/bash
# Exercises for Lesson 14: Git Hooks Advanced
# Topic: Git
# Solutions to practice problems from the lesson.

# === Exercise 1: Set Up Husky with lint-staged ===
# Problem: Configure Husky and lint-staged in a Node.js project
# so that only staged files are linted on each commit.
exercise_1() {
    echo "=== Exercise 1: Set Up Husky with lint-staged ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Initialize a Node.js project"
    echo "  mkdir hooks-lab && cd hooks-lab"
    echo "  git init"
    echo "  npm init -y"
    echo ""
    echo "  # Step 2: Install Husky and lint-staged"
    echo "  npm install --save-dev husky lint-staged eslint prettier"
    echo ""
    echo "  # Step 3: Initialize Husky"
    echo "  npx husky init"
    echo "  # Creates .husky/ directory with a sample pre-commit hook"
    echo ""
    echo "  # Step 4: Configure the pre-commit hook to run lint-staged"
    echo "  echo 'npx lint-staged' > .husky/pre-commit"
    echo ""
    echo "  # Step 5: Configure lint-staged in package.json"
    echo "  # Add to package.json:"
    echo "  # {"
    echo "  #   \"lint-staged\": {"
    echo "  #     \"*.{js,ts,tsx}\": [\"eslint --fix\", \"prettier --write\"],"
    echo "  #     \"*.{json,md,yml}\": [\"prettier --write\"]"
    echo "  #   }"
    echo "  # }"
    echo ""
    echo "  # Step 6: Test the setup"
    echo "  echo 'const x = 1;; // double semicolon' > app.js"
    echo "  git add app.js"
    echo "  git commit -m 'test: trigger lint-staged'"
    echo "  # lint-staged runs eslint --fix on app.js before committing"
    echo "  # If eslint finds unfixable errors, the commit is blocked"
    echo ""
    echo "  # Step 7: Verify lint-staged only processes staged files"
    echo "  echo 'const bad = ;' > other.js    # Not staged"
    echo "  echo 'const good = 1;' > app.js     # Will be staged"
    echo "  git add app.js                       # Only app.js is staged"
    echo "  git commit -m 'feat: update app'"
    echo "  # lint-staged only checks app.js (staged), ignores other.js"
    echo ""
    echo "Key takeaway:"
    echo "  Husky manages Git hooks via .husky/ directory (committed to repo)."
    echo "  lint-staged runs linters ONLY on staged files, keeping pre-commit"
    echo "  hooks fast even in large projects."
}

# === Exercise 2: pre-commit Framework Configuration ===
# Problem: Set up the pre-commit framework with multiple hooks
# for a polyglot project (Python + Shell + YAML).
exercise_2() {
    echo "=== Exercise 2: pre-commit Framework Configuration ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Install pre-commit"
    echo "  pip install pre-commit"
    echo "  # Or: brew install pre-commit"
    echo ""
    echo "  # Step 2: Create .pre-commit-config.yaml"
    echo "  cat > .pre-commit-config.yaml << 'EOF'"
    echo "repos:"
    echo "  - repo: https://github.com/pre-commit/pre-commit-hooks"
    echo "    rev: v4.6.0"
    echo "    hooks:"
    echo "      - id: trailing-whitespace"
    echo "      - id: end-of-file-fixer"
    echo "      - id: check-yaml"
    echo "      - id: check-json"
    echo "      - id: check-added-large-files"
    echo "        args: ['--maxkb=500']"
    echo "      - id: detect-private-key"
    echo "      - id: check-merge-conflict"
    echo ""
    echo "  - repo: https://github.com/astral-sh/ruff-pre-commit"
    echo "    rev: v0.4.4"
    echo "    hooks:"
    echo "      - id: ruff"
    echo "        args: [--fix]"
    echo "      - id: ruff-format"
    echo ""
    echo "  - repo: https://github.com/shellcheck-py/shellcheck-py"
    echo "    rev: v0.10.0.1"
    echo "    hooks:"
    echo "      - id: shellcheck"
    echo "EOF"
    echo ""
    echo "  # Step 3: Install the hooks"
    echo "  pre-commit install"
    echo "  pre-commit install --hook-type commit-msg"
    echo ""
    echo "  # Step 4: Run against all files (initial check)"
    echo "  pre-commit run --all-files"
    echo ""
    echo "  # Step 5: Test with a violation"
    echo "  echo 'import os  ' > test.py    # Trailing whitespace"
    echo "  git add test.py"
    echo "  git commit -m 'test: trigger hooks'"
    echo "  # trailing-whitespace hook fixes the file and fails the commit"
    echo "  # Re-add and commit: the fixed file passes on the second attempt"
    echo ""
    echo "  # Step 6: Update hook versions"
    echo "  pre-commit autoupdate"
    echo ""
    echo "Key takeaway:"
    echo "  The pre-commit framework is language-agnostic and uses remote"
    echo "  repositories for hook definitions. It caches tool installations"
    echo "  and runs hooks in isolated environments."
}

# === Exercise 3: Custom Hook Chain with Orchestrator ===
# Problem: Build a pre-commit hook system that runs multiple checks
# in a modular directory structure with proper error handling.
exercise_3() {
    echo "=== Exercise 3: Custom Hook Chain with Orchestrator ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Step 1: Create the hook directory structure"
    echo "  mkdir -p .githooks/pre-commit.d"
    echo ""
    echo "  # Step 2: Create the orchestrator script"
    echo "  cat > .githooks/pre-commit << 'HOOKEOF'"
    echo "#!/bin/bash"
    echo "HOOKS_DIR=\"\$(dirname \"\$0\")/pre-commit.d\""
    echo "EXIT_CODE=0"
    echo ""
    echo "for hook in \"\$HOOKS_DIR\"/*; do"
    echo "    if [ -x \"\$hook\" ]; then"
    echo "        echo \"Running \$(basename \"\$hook\")...\""
    echo "        \"\$hook\""
    echo "        if [ \$? -ne 0 ]; then"
    echo "            echo \"FAIL: \$(basename \"\$hook\")\""
    echo "            EXIT_CODE=1"
    echo "        else"
    echo "            echo \"PASS: \$(basename \"\$hook\")\""
    echo "        fi"
    echo "    fi"
    echo "done"
    echo ""
    echo "exit \$EXIT_CODE"
    echo "HOOKEOF"
    echo "  chmod +x .githooks/pre-commit"
    echo ""
    echo "  # Step 3: Create individual hook scripts"
    echo ""
    echo "  # 01 - Prevent direct commits to main"
    echo "  cat > .githooks/pre-commit.d/01-branch-check.sh << 'HOOKEOF'"
    echo "#!/bin/bash"
    echo "BRANCH=\$(git symbolic-ref --short HEAD)"
    echo "if [ \"\$BRANCH\" = \"main\" ] || [ \"\$BRANCH\" = \"production\" ]; then"
    echo "    echo \"Direct commits to \$BRANCH are not allowed. Use a PR.\""
    echo "    exit 1"
    echo "fi"
    echo "HOOKEOF"
    echo ""
    echo "  # 02 - Detect debug statements"
    echo "  cat > .githooks/pre-commit.d/02-no-debug.sh << 'HOOKEOF'"
    echo "#!/bin/bash"
    echo "if git diff --cached --diff-filter=ACM | grep -E '(console\\.log|debugger|import pdb|breakpoint\\(\\))' > /dev/null; then"
    echo "    echo \"Debug statements found in staged changes!\""
    echo "    exit 1"
    echo "fi"
    echo "HOOKEOF"
    echo ""
    echo "  # 03 - Check for merge conflict markers"
    echo "  cat > .githooks/pre-commit.d/03-no-conflict-markers.sh << 'HOOKEOF'"
    echo "#!/bin/bash"
    echo "if git diff --cached | grep -E '^[+].*(<<<<<<|======|>>>>>>)' > /dev/null; then"
    echo "    echo \"Merge conflict markers found!\""
    echo "    exit 1"
    echo "fi"
    echo "HOOKEOF"
    echo ""
    echo "  chmod +x .githooks/pre-commit.d/*"
    echo ""
    echo "  # Step 4: Configure Git to use the hooks directory"
    echo "  git config core.hooksPath .githooks"
    echo ""
    echo "  # Step 5: Test the hook chain"
    echo "  git add . && git commit -m 'chore: add hook infrastructure'"
    echo "  # All three hooks run in order (01, 02, 03)"
    echo ""
    echo "Key takeaway:"
    echo "  An orchestrator pattern keeps hooks modular and maintainable."
    echo "  Each hook is a standalone script in pre-commit.d/. The orchestrator"
    echo "  runs them in sorted order and collects exit codes."
}

# === Exercise 4: Commit Message Enforcement ===
# Problem: Create a commit-msg hook that enforces the Conventional
# Commits format and set up commitlint for a team project.
exercise_4() {
    echo "=== Exercise 4: Commit Message Enforcement ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # === Option A: Custom shell script ==="
    echo ""
    echo "  # Step 1: Create a commit-msg hook"
    echo "  cat > .githooks/commit-msg << 'HOOKEOF'"
    echo "#!/bin/bash"
    echo "COMMIT_MSG_FILE=\$1"
    echo "FIRST_LINE=\$(head -1 \"\$COMMIT_MSG_FILE\")"
    echo ""
    echo "PATTERN=\"^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\(.+\\))?(!)?: .{1,72}\$\""
    echo ""
    echo "if ! echo \"\$FIRST_LINE\" | grep -qE \"\$PATTERN\"; then"
    echo "    echo \"Invalid commit message format!\""
    echo "    echo \"Expected: <type>(<scope>): <description>\""
    echo "    echo \"Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert\""
    echo "    echo \"Your message: \$FIRST_LINE\""
    echo "    exit 1"
    echo "fi"
    echo "HOOKEOF"
    echo "  chmod +x .githooks/commit-msg"
    echo ""
    echo "  # Step 2: Test with valid and invalid messages"
    echo "  echo 'test' > test.txt && git add test.txt"
    echo "  git commit -m 'bad message'"
    echo "  # REJECTED: Invalid commit message format!"
    echo ""
    echo "  git commit -m 'feat: add test file'"
    echo "  # ACCEPTED: matches the pattern"
    echo ""
    echo "  # === Option B: commitlint (Node.js projects) ==="
    echo ""
    echo "  # Step 3: Install commitlint"
    echo "  npm install --save-dev @commitlint/cli @commitlint/config-conventional"
    echo ""
    echo "  # Step 4: Create commitlint.config.mjs"
    echo "  # export default {"
    echo "  #   extends: ['@commitlint/config-conventional'],"
    echo "  #   rules: {"
    echo "  #     'subject-max-length': [2, 'always', 72],"
    echo "  #     'body-max-line-length': [2, 'always', 100]"
    echo "  #   }"
    echo "  # };"
    echo ""
    echo "  # Step 5: Wire commitlint to the commit-msg hook"
    echo "  echo 'npx commitlint --edit \"\$1\"' > .husky/commit-msg"
    echo ""
    echo "  # Step 6: Test"
    echo "  echo 'invalid' | npx commitlint"
    echo "  # Errors: type may not be empty, subject may not be empty"
    echo ""
    echo "  echo 'feat(api): add pagination' | npx commitlint"
    echo "  # Passes all rules"
    echo ""
    echo "Key takeaway:"
    echo "  Commit message hooks enforce consistency across a team."
    echo "  Custom scripts are lightweight; commitlint is more powerful"
    echo "  with configurable rules, scopes, and integration with CI."
}

# === Exercise 5: Server-Side Hook Simulation ===
# Problem: Simulate a pre-receive hook that enforces policies
# like no force push to main, no large files, and branch naming.
exercise_5() {
    echo "=== Exercise 5: Server-Side Hook Simulation ==="
    echo ""
    echo "Solution commands:"
    echo ""
    echo "  # Server-side hooks run on the Git server (GitHub, GitLab, self-hosted)."
    echo "  # We simulate one locally using a pre-push hook."
    echo ""
    echo "  # Step 1: Create a pre-push hook that simulates server policies"
    echo "  cat > .githooks/pre-push << 'HOOKEOF'"
    echo "#!/bin/bash"
    echo "# Simulate server-side pre-receive policies"
    echo ""
    echo "REMOTE=\$1"
    echo "URL=\$2"
    echo ""
    echo "while read local_ref local_sha remote_ref remote_sha; do"
    echo "    BRANCH=\$(echo \"\$remote_ref\" | sed 's|refs/heads/||')"
    echo ""
    echo "    # Policy 1: No force push to main or production"
    echo "    if echo \"\$BRANCH\" | grep -qE '^(main|production)\$'; then"
    echo "        if [ \"\$remote_sha\" != \"0000000000000000000000000000000000000000\" ]; then"
    echo "            MERGE_BASE=\$(git merge-base \"\$remote_sha\" \"\$local_sha\" 2>/dev/null)"
    echo "            if [ \"\$MERGE_BASE\" != \"\$remote_sha\" ]; then"
    echo "                echo \"ERROR: Force push to \$BRANCH is not allowed!\""
    echo "                exit 1"
    echo "            fi"
    echo "        fi"
    echo "    fi"
    echo ""
    echo "    # Policy 2: Branch naming convention"
    echo "    if ! echo \"\$BRANCH\" | grep -qE '^(main|develop|feature/.*|fix/.*|hotfix/.*|release/.*)\$'; then"
    echo "        echo \"ERROR: Branch '\$BRANCH' does not follow naming convention.\""
    echo "        echo \"Allowed: main, develop, feature/*, fix/*, hotfix/*, release/*\""
    echo "        exit 1"
    echo "    fi"
    echo ""
    echo "    # Policy 3: No large files (>5MB)"
    echo "    MAX_SIZE=5242880"
    echo "    if [ \"\$local_sha\" != \"0000000000000000000000000000000000000000\" ]; then"
    echo "        LARGE=\$(git rev-list --objects \"\$remote_sha..\$local_sha\" 2>/dev/null | \\"
    echo "            git cat-file --batch-check='%(objecttype) %(objectsize) %(rest)' | \\"
    echo "            grep ^blob | awk \"\\\$2 > \$MAX_SIZE {print \\\$3, \\\$2}\")"
    echo "        if [ -n \"\$LARGE\" ]; then"
    echo "            echo \"ERROR: Files exceeding 5MB detected:\""
    echo "            echo \"\$LARGE\""
    echo "            echo \"Use Git LFS for large files.\""
    echo "            exit 1"
    echo "        fi"
    echo "    fi"
    echo "done"
    echo ""
    echo "echo \"All push policies passed.\""
    echo "HOOKEOF"
    echo "  chmod +x .githooks/pre-push"
    echo ""
    echo "  # Step 2: Test branch naming policy"
    echo "  git switch -c my-random-branch"
    echo "  echo 'test' > test.txt && git add . && git commit -m 'test: policy check'"
    echo "  git push origin my-random-branch"
    echo "  # ERROR: Branch 'my-random-branch' does not follow naming convention."
    echo ""
    echo "  git switch -c feature/valid-name"
    echo "  git push origin feature/valid-name"
    echo "  # Passes -- name matches 'feature/*'"
    echo ""
    echo "Key takeaway:"
    echo "  Server-side hooks are the last line of defense. They cannot be"
    echo "  bypassed with --no-verify. On hosted platforms (GitHub, GitLab),"
    echo "  use branch protection rules and webhooks instead of custom hooks."
}

# Run all exercises
exercise_1
echo ""
exercise_2
echo ""
exercise_3
echo ""
exercise_4
echo ""
exercise_5
echo ""
echo "All exercises completed!"
