# dbt project configuration for the practical pipeline example.
# Adapted from Data_Engineering Lesson 14 ยง5.

name: ecommerce_pipeline
version: "1.0.0"
config-version: 2

profile: ecommerce_pipeline

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: target
clean-targets:
  - target
  - dbt_packages
