# dbt profiles — connects to the local warehouse PostgreSQL.
# In production, replace with Snowflake / BigQuery / Redshift credentials.

ecommerce_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('WAREHOUSE_DB_HOST', 'warehouse-db') }}"
      port: "{{ env_var('WAREHOUSE_DB_PORT', '5432') | int }}"
      user: "{{ env_var('WAREHOUSE_DB_USER', 'warehouse') }}"
      pass: "{{ env_var('WAREHOUSE_DB_PASSWORD', 'warehouse_pass') }}"
      dbname: "{{ env_var('WAREHOUSE_DB_NAME', 'analytics') }}"
      schema: public
      threads: 2
